ngx-formly/ngx-formly

src/components/formly.common.component.ts
src/components/formly.field.ts
src/components/formly.form.ts
src/hello.ts
src/services/control.service.ts
src/services/field.base.ts
src/services/formly.config.ts
src/services/formly.messages.ts
src/template.html
src/templates/checkbox.html
src/templates/field.ts
src/templates/formlyfield.checkbox.ts
src/templates/formlyfield.input.ts
src/templates/input.html
typings/ng2-formly.d.ts
typings/tsd.d.ts

feat (FormlyConfig) Implementation of FormlyConfig

feat (typings) Added Typing support

---

index.html
src/components/formly.form.ts
src/hello.ts
src/template.html
src/templates/checkbox.html
src/templates/field.ts
src/templates/formlyfield.input.ts
src/templates/formlyfield.textarea.ts
src/templates/input.html
src/templates/radio.html
src/templates/select.html
src/templates/textarea.html

docs(custom type): Added Toggle Custom Type to the Example

feat(templates): Templates updated to reflect Bootstrap 4

---

package.json
src/components/formly.field.ts
src/components/formly.form.ts
src/services/control.service.ts
src/templates/formlyfield.radio.ts
src/templates/formlyfield.select.ts
tsconfig.json

Changed loadIntoLocation to loadNextToLocation.

Update angular to version Beta 17

---

package.json

Issue with npm script flow.compile:system on windows
#29

fix(build): fix #29 on windows

---

.gitignore
demo/hello.ts
src/components/formly.field.ts
src/services/control.service.ts
src/templates.ts
src/templates/formlyfield.input.ts
src/templates/formlyfield.multicheckbox.ts
src/templates/templates.ts
tsconfig.json

Supporting Multi Checkbox
it addresses https://github.com/formly-js/ng2-formly/issues/9

feat(components): Supporting Multi Checkbox

---

demo/hello.ts

Updated version in the example.

---

demo/hello.ts
demo/template.html
src/components/formly.common.component.ts
src/components/formly.field.group.ts
src/components/formly.field.ts
src/components/formly.form.ts
src/services/formly.config.ts
src/services/formly.event.emitter.ts
src/services/formly.expression.ts
src/services/formly.field.builder.ts
src/services/formly.field.delegates.ts
src/services/formly.providers.ts
src/templates/field.ts
src/templates/formlyfield.checkbox.ts
src/templates/formlyfield.input.ts
src/templates/formlyfield.multicheckbox.ts
src/templates/formlyfield.radio.ts
src/templates/formlyfield.select.ts
src/templates/formlyfield.textarea.ts

This Commits provides a temporary fix for two binding issue (see#45 for more details). This workaround for observable change propagation needs to be removed once issue with angular two way binding for dynamic  component is fixed. See angular/angular#8903 for more.
This Pull request also has refactoring changes.

fix(formBinding): Fix for two way binding issue

---

README.md

Fix imports in code examples & typos

docs(readme): Make minor corrections

---

demo/hello.ts
src/components/formly.common.component.ts
src/components/formly.field.group.ts
src/components/formly.field.ts
src/components/formly.form.ts
src/services/formly.field.delegates.ts
src/templates/field.ts
src/templates/formlyfield.checkbox.ts
src/templates/formlyfield.multicheckbox.ts
src/templates/formlyfield.radio.ts

Fix for two way binding of radio button mentioned in #54

fix(radiobutton): Fixes #54 issue with two way binding of radio button

---

demo/hello.ts
package.json
src/components/formly.common.component.ts
src/components/formly.field.group.ts
src/components/formly.field.ts
src/components/formly.form.ts
src/services/formly.field.delegates.ts
src/templates/field.ts
src/templates/formlyfield.checkbox.ts
src/templates/formlyfield.input.ts
src/templates/formlyfield.multicheckbox.ts
src/templates/formlyfield.radio.ts
src/templates/formlyfield.select.ts
src/templates/formlyfield.textarea.ts
tsconfig.json

Fixes #53 by using angular renderer for modifying native element instead of direct modification.
This pull request is dependent on https://github.com/formly-js/ng2-formly/pull/60

Fixes #53 by using angular renderer

---

.config/bundle-system.js
demo/hello.ts
demo/index.html
package.json
src/components/formly.common.component.ts
src/components/formly.field.group.ts
src/components/formly.form.ts
src/services/formly.messages.ts
src/templates/field.ts
src/templates/formlyfield.checkbox.ts
src/templates/formlyfield.input.ts
src/templates/formlyfield.multicheckbox.ts
src/templates/formlyfield.radio.ts
src/templates/formlyfield.select.ts
src/templates/formlyfield.textarea.ts
typings/ng2-formly.d.ts

closes #70 
This is still work in progress.

Initial commit for ng2-formly with @angular/forms which replaces deprecated forms api

---

src/templates/field.ts
src/templates/formlyfield.radio.ts

Fix #72 where radio button control was broken because of migration to new @angular/forms module

fix(radio): closes #72

---

demo/hello.ts
src/templates.ts

fix #81 by exporting SingleFocusDispatcher via templates thus is also available via index.ts

fix(radio): fix #81 by exporting SingleFocusDispatcher via templates

---

demo/hello.ts
demo/template.html
gulpfile.js
src/components/formly.field.ts
src/components/formly.form.ts
src/core.ts
src/services/formly.config.ts
src/services/formly.field.builder.ts
src/templates/field.ts
src/templates/formlyBootstrap.ts
src/templates/formlyfield.checkbox.ts
src/templates/formlyfield.input.ts
src/templates/formlyfield.multicheckbox.ts
src/templates/formlyfield.radio.ts
src/templates/formlyfield.select.ts
src/templates/formlyfield.textarea.ts
src/templates/templates.ts

Add ng2Module support

---

CHANGELOG.MD
demo/index.html
src/templates/formlyfield.checkbox.ts
src/templates/formlyfield.multicheckbox.ts
src/templates/formlyfield.radio.ts
src/templates/formlyfield.select.ts

fix #82 by adding form-control in checkbox, select, radio and multicheckbox templates also added form-group in select template.

fix(style): fix #82 by adding form-control & form-group css classes where missing

---

demo/hello.ts
src/components/formly.form.ts
src/templates/formlyfield.input.ts

Note: I also updated angular to v2.0 except `@angular/forms`

fix(validation): validation occurs before the user interacts.

---

demo/index.html
package.json
src/components/formly.common.component.ts
src/components/formly.field.ts
src/components/formly.form.ts
src/services/formly.config.ts
src/services/formly.field.delegates.ts
src/services/formly.messages.ts
src/templates/field.ts
src/templates/formlyfield.checkbox.ts
src/templates/formlyfield.input.ts
src/templates/formlyfield.multicheckbox.ts
src/templates/formlyfield.radio.ts
src/templates/formlyfield.select.ts
src/templates/formlyfield.textarea.ts

feat(angular): Add support for angular@2.0

---

demo/hello.ts
src/components/formly.field.ts
src/services/formly.config.ts
src/templates/field.ts

This will make sure that Validations can be in an array, and thus JSON can be used to populate the form with validations.

feat(validation) Support for Validation Array fixes #41

---

demo/hello.ts
src/core.ts
src/services/formly.config.ts
src/services/formly.messages.ts
src/services/formly.providers.ts
src/templates.ts
src/templates/formlyBootstrap.ts

```js
FormlyModule.forRoot({
types: TYPES;
validators: VALIDATORS;
validationMessages: VALIDATION_MESSAGES;
}),
```

feat(FormlyModule): improve registering types, validators and validationMessage.

---

package.json
src/core.ts
src/templates/formlyBootstrap.ts

fix(FormlyModule): use CommonModule instead of BrowserModule.

---

README.md

fix https://github.com/formly-js/ng2-formly/issues/114

docs(bootstrap): Update Documentation with bootstraping ng2-formly

---

.config/webpack.demo.js
demo/hello.ts
demo/index.html
gulpfile.js
package.json
tsconfig.json

use `npm run demo` instead of `gulp play`

feat(demo): use webpack

---

demo/hello.ts
src/components/formly.form.ts
src/templates/wrappers/description.ts
src/templates/wrappers/fieldset.ts
src/templates/wrappers/label.ts
src/templates/wrappers/message-validation.ts

fix(#140): assign default templateOptions.

---

demo/hello.ts
src/components/formly.field.config.ts
src/templates/field.type.ts
src/templates/types/input.ts
src/templates/types/multicheckbox.ts
src/templates/types/radio.ts
src/templates/types/select.ts
src/templates/types/textarea.ts

feat(Lifecycle Hooks) Integrate the fields with lifecycle hooks

---

demo/hello.ts
src/components/formly.field.config.ts
src/components/formly.field.ts
src/components/formly.form.ts

feat(Default Value) Add default Value functionility

---

demo/hello.ts
src/services/formly.config.ts

feat(Wrappers) Types property can be set to wrappers

---

demo/hello.ts
src/components/formly.field.config.ts
src/components/formly.form.ts

feat(Validation) add Validators API

---

demo/hello.ts
src/components/formly.field.config.ts
src/components/formly.form.ts
src/templates/types/checkbox.ts

In the demo, username has all kinds of formly validation working together
i) templateOptions `required: true`
ii) validators validation `Validators.maxLength`
iii) Custom sync validation `custom`
iv) Async validation

feat(Validation) Validation property in Validators property

---

demo/hello.ts
demo/repeatedSection.ts
src/components/formly.field.config.ts
src/components/formly.field.ts
src/components/formly.form.ts

Thanks @thiagogjt for your [comment](https://github.com/formly-js/ng2-formly/issues/189#issuecomment-257012389) on #189

feat(FormArray) Support for FormArray, demo with repeated section

---

demo/hello.ts
src/core/components/formly.field.config.ts
src/core/components/formly.field.ts
src/core/components/formly.group.ts
src/core/core.ts
src/core/services/formly.config.ts
src/ui-bootstrap/ui-bootstrap.config.ts

feat(FieldWrapper) FieldWrapper

---

demo/horizontal.wrapper.ts
demo/index.html
demo/repeatedSection.ts
src/core/components/formly.form.ts
src/core/components/formly.group.ts

Initial support for flexbox #215

feat(FormlyField) Support for flexbox classes

---

demo/hello.ts
src/core/components/formly.attributes.ts
src/core/components/formly.field.config.ts

feat(Events) add events to TemplateOptions

---

demo/hello.ts
demo/index.html
src/core/components/formly.field.ts
src/core/services/formly.config.ts
src/ui-bootstrap/run/addon.ts
src/ui-bootstrap/run/description.ts
src/ui-bootstrap/run/validation.ts
src/ui-bootstrap/ui-bootstrap.config.ts
src/ui-bootstrap/ui-bootstrap.module.ts
src/ui-bootstrap/wrappers/addons.ts
src/ui-bootstrap/wrappers/label.ts

feat(templateManipulators) Add template Manipulators functionality

---

demo/hello.ts
demo/template.html
demo/toggle.ts
src/core/components/formly.field.ts
src/core/components/formly.form.ts
src/core/templates/field.ts

Closes #203
#172 can be worked on with this change

feat(options) options part1 (example of formState-readOnly

---

demo/template.html
src/core/components/formly.form.ts

feat(formReset) Form Reset functionality using options

---

demo/hello.ts
src/core/components/formly.field.config.ts
src/core/services/formly.form.builder.ts
src/ui-bootstrap/types/checkbox.ts

**BREAKING CHANGE**
Closes #165

feat(AsyncValidator) Add asyncValidator instead of asyncValidation

---

CHANGELOG.MD
demo/hello.ts
package.json

chore(upgrade): upgrade version

---

demo/hello.ts
package.json

chore(upgrade): Update to 2.0.0-beta.13

---

src/core/components/formly.form.ts
src/core/services/formly.config.ts
src/core/services/formly.form.builder.ts

Feature
Field Transform as in angular-formly Closes #246 

feat(FieldTransform) Implementation of Field Transform

---

karma.conf.js
package.json
yarn.lock

test(test-watch): show interim coverage report

---

demo/toggle.ts
src/core/components/formly.form.ts

fix(#265): [Field type] get model value using `model[key]`

---

demo/hello.ts
demo/horizontal.wrapper.ts
demo/panel.wrapper.ts
demo/toggle.ts
src/core/components/formly.field.spec.ts
src/core/templates/field.ts
src/ui-bootstrap/run/addon.ts
src/ui-bootstrap/run/description.ts
src/ui-bootstrap/run/validation.ts
src/ui-bootstrap/types/checkbox.ts
src/ui-bootstrap/types/input.ts
src/ui-bootstrap/types/multicheckbox.ts
src/ui-bootstrap/types/radio.ts
src/ui-bootstrap/types/select.ts
src/ui-bootstrap/types/textarea.ts
src/ui-bootstrap/wrappers/addons.ts
src/ui-bootstrap/wrappers/description.ts
src/ui-bootstrap/wrappers/label.ts

feat(templateOptions): deprecate 'templateOptions' in favor of 'to'.

---

demo/toggle.ts
package.json
src/core/components/formly.form.ts
src/core/templates/field.ts

feat(formState): add `formState` in FieldType

---

demo/hello.ts
src/core/components/formly.field.config.ts
src/core/services/formly.form.builder.spec.ts
src/core/services/formly.form.builder.ts
src/ui-bootstrap/formly.validation-message.spec.ts
src/ui-bootstrap/formly.validation-message.ts
src/ui-bootstrap/types/checkbox.ts

feat(#269): custom Validators with `expression + message`

---

demo/hello.ts
demo/repeatedSection.ts
demo/template.html
src/core/components/formly.field.ts
src/core/components/formly.form.ts
src/core/components/formly.group.ts
src/core/services/formly.field.delegates.ts
src/core/templates/field.ts

feat(formState): support `formState` in expressionProperties

---

demo/hello.ts
src/core/services/formly.form.builder.ts
src/ui-bootstrap/wrappers/addons.ts

fix(addon): add `addonRight`

---

demo/hello.ts
src/ui-bootstrap/types/select.ts

Feature
Grouped Select support

feat(GroupedSelect) Support Grouped Select

---

demo/hello.ts
src/core/components/formly.field.config.ts
src/core/templates/field.type.ts

feat
Have access to key params like form, field, model, option

feat(Lifecycle) pass key params to lifecycle events

---

src/core/services/formly.form.builder.spec.ts

test(AsyncValidation) testing asyncValidation

---

.npmignore

Allows us to build from the npm artifact
You need to copy over the webpack and typescript configuration
The configuration is downloaded on npm install.
- [?] The commit messages follow our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
I think that we could use a lookBack regex on the .config folder but this is my lazy version. …

These need to be added if we want to build locally issue #308

---

CHANGELOG.MD

I used github_changelog_generator to generate the changelog automatically

chore(changelog) update change log

---

src/core/services/formly.form.builder.spec.ts
src/core/services/formly.form.builder.ts

**What kind of change does this PR introduce? Bug fix
fixed #317

fix(FieldExpression): init field expression for all fields

---

src/core/components/formly.field.ts
src/core/components/formly.form.ts
src/core/services/formly.form.builder.spec.ts
src/core/services/formly.form.builder.ts

**NOTE** To be merged after #319

[270] execute field expression during form build

---

demo/hello.ts
src/core/components/formly.field.config.ts
src/core/components/formly.field.ts
src/core/services/formly.form.builder.ts

http://docs.angular-formly.com/docs/field-configuration-object#hide-boolean

feat(field): add hide option

---

demo/hello.ts
src/core/components/formly.field.config.ts
src/core/services/formly.form.builder.ts

feat(field): allow providing custom formControl through field config

---

src/core/components/formly.field.config.ts

fix(implicitAny) fixing implicitAny error

---

.gitignore
src/core/components/formly.field.ts
src/core/components/formly.group.ts
src/core/services/formly.form.builder.ts
src/core/templates/field.ts

feat(field): attach created FormControls to field

---

src/core/services/formly.form.builder.ts

fix(form-build): inject missing options arg.

---

src/core/components/formly.field.config.ts
src/core/components/formly.field.ts

feat(wrapper) deprecate wrapper

---

demo/hello.ts
src/core/components/formly.field.config.ts
src/ui-bootstrap/formly.validation-message.ts

feat(Validation) supporting field.validation.messages

---

src/core/components/formly.field.ts

fix(Validation): Hidden fields should be marked as valid

---

src/core/components/formly.field.ts

fix(wrapper): add field key to warn

---

src/core/components/formly.form.ts
src/core/components/formly.group.ts

fix(#330): ensure buildForm is called only once per form

---

demo/repeatedSection.ts

fix(#344): [fieldArray] emit form valueChanges

---

demo/hello.ts
src/core/services/formly.form.builder.ts
src/core/utils.ts

fix(Array) Array in property access

---

demo/hello.ts

fix(date-validation): allow empty value.

---

demo/repeatedSection.ts

fix(RepeatComponent): fixed resetModel with FormArrays

---

.all-contributorsrc
.config/webpack.build.js
.config/webpack.demo.js
CHANGELOG.MD
CONTRIBUTING.md
README.md
demo/hello.ts
demo/template.html
package.json

chore(upgrade) upgrade to RC

---

src/core/components/formly.field.ts
src/core/services/formly.event.emitter.ts

**What kind of change does this PR introduce? Bug fix, feature**

feat(FormlyField): destroy all componentRefs + _subscriptions.

---

src/core/components/formly.attributes.spec.ts
src/core/components/formly.attributes.ts
src/core/components/formly.field.config.ts
src/ui-bootstrap/types/checkbox.ts
src/ui-bootstrap/types/input.ts
src/ui-bootstrap/types/multicheckbox.ts
src/ui-bootstrap/types/radio.ts
src/ui-bootstrap/types/select.ts
src/ui-bootstrap/types/textarea.ts

feat(FormlyAttributes): render field id and name.

---

src/core/services/formly.form.builder.spec.ts
src/core/services/formly.form.builder.ts

fix(field): fixed assign default value for nested form.

---

.travis.yml
package.json
src/core/components/formly.field.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/368)

fix(FormlyField): check field before removing the emitter.

---

index.ts

Please see #372 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/373)

fix(#372): export everything from ./src/index.ts

---

demo/hello.ts
src/core/core.ts
src/core/services/formly.config.ts

fixed #375
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/378)

feat(config): export ConfigOption.

---

.travis.yml
package.json
src/core/core.ts
yarn.lock

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/380)

feat(module): add forChild for child module.

---

src/core/components/formly.field.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/381)

feat(rxjs): better usage of rxjs operators.

---

src/core/services/formly.form.builder.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/386)

fix(validation): allow set validation for field group.

---

src/core/services/formly.form.builder.spec.ts
src/core/services/formly.form.builder.ts
src/core/utils.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/387)

fix(field): ignore assigning defaultValue only when it's undefined.

---

src/core/services/formly.config.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/388)

feat(FormlyConfig): introduce `addConfig` method

---

src/core/components/formly.form.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/392)

feat(FormlyField): allow setting className for field which contains fieldGroup

---

package.json

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/385)

feat(deps): allow angular v4.

---

CHANGELOG.md
demo/hello.ts
package.json

**What kind of change does this PR introduce? update**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/393)

chore(upgrade) update version to rc-2.

---

src/core/components/formly.form.ts

Reverts formly-js/ng-formly#392
Fix #404
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/405)

Revert "feat(FormlyField): allow setting className for fieldGroup

---

src/core/components/formly.field.ts
src/core/services/formly.form.builder.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/417)

fix(#406): workaround for hideExpression.

---

demo/src/formly/types/repeatedSection.ts
package.json

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/422)

fix(#421): avoid using internal function in RepeatComponent.

---

src/core/components/formly.field.spec.ts
src/core/components/formly.field.ts
src/core/services/formly.form.builder.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/425)

feat(expressionProperties): eval evalExpression only when the express changed

---

src/core/components/formly.field.spec.ts
src/core/components/formly.field.ts
tsconfig.json

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/424)

fix(hideExpression): ensure adding/removing form control for nested keys.

---

demo/src/formly/types/repeatedSection.ts
package.json

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/427)

fix(#426): update Validity when form is builded

---

package.json
tsconfig.build.json
tsconfig.json
yarn.lock

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/433)

build(ts): enable --importHelpers.

---

demo/src/app.component.html
demo/src/app.component.ts
demo/src/formly/index.ts
package.json
src/core/services/formly.config.ts
src/core/services/formly.form.builder.ts
src/core/templates/field.ts
yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/434)

feat(validation): introduce showError to check form validation

---

CHANGELOG.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/440)

 chore(CHANGELOG): Update changelog

---

src/core/components/formly.form.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/441)

feat(options form): allow using custom resetModel + updateInitialValue

---

README.md
core.ts
demo/src/app.component.ts
demo/src/app.module.ts
demo/src/formly/index.ts
demo/src/formly/types/repeatedSection.ts
demo/src/formly/types/toggle.ts
demo/src/formly/wrappers/horizontal.wrapper.ts
demo/src/formly/wrappers/panel.wrapper.ts
package.json
tsconfig.json
ui-bootstrap.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/443)

docs(import): use `ng-formly` instead of `ng-formly/core`

---

CHANGELOG.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/447)

chore(CHANGELOG): Update changelog

---

src/ui-bootstrap/types/multicheckbox.ts

448
Bug fix
Validators are not evaluated.  https://github.com/formly-js/ng-formly/issues/448#issuecomment-309195714
Validators are evaluated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/450)

fix(FormlyFieldMultiCheckbox): supply validators to control

---

.config/webpack.build.js
package.json
yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/454)

build(webpack): update to v3.0

---

demo/src/app.component.html
demo/src/formly/types/toggle.ts
demo/src/formly/wrappers/horizontal.wrapper.ts
demo/src/formly/wrappers/panel.wrapper.ts
src/core/components/formly.field.spec.ts
src/ui-bootstrap/formly.validation-message.ts
src/ui-bootstrap/types/checkbox.ts
src/ui-bootstrap/types/multicheckbox.ts
src/ui-bootstrap/types/radio.ts
src/ui-bootstrap/types/select.ts
src/ui-bootstrap/wrappers/addons.ts
src/ui-bootstrap/wrappers/description.ts
src/ui-bootstrap/wrappers/label.ts
tslint.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/455)

style(tslint): add `angular-whitespace` rule

---

demo/src/app.component.ts
demo/src/formly/types/repeatedSection.ts
package.json
yarn.lock

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/456)

fix(RepeatComponent): take account of validation object

---

demo/src/services/validation.service.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/457)

fix(Validation): skip validation if value not provided

---

src/core/components/formly.attributes.ts
src/core/components/formly.field.config.ts
src/core/components/formly.field.ts
src/core/components/formly.form.spec.ts
src/core/components/formly.group.ts
src/core/services/formly.config.ts
src/core/services/formly.event.emitter.ts
src/core/services/formly.form.builder.ts
src/core/services/formly.validation-messages.ts
src/core/templates/field.ts
src/core/templates/field.type.ts
src/core/utils.ts
src/ui-bootstrap/formly.validation-message.ts
src/ui-bootstrap/types/multicheckbox.ts
src/ui-bootstrap/types/select.ts
src/ui-bootstrap/wrappers/addons.ts
tsconfig.build.json

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/458)

 feat(typescript): improve typings

---

src/core/src/components/formly.attributes.spec.ts
src/core/src/components/formly.attributes.ts
src/core/src/components/formly.field.ts

fixed #462
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/498)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/498)

feat: replace deprecated `Renderer` by `Renderer2`

---

src/core/src/components/formly.field.spec.ts
src/core/src/components/formly.field.ts
src/ui-bootstrap/src/wrappers/addons.ts
src/ui-bootstrap/src/wrappers/description.ts
src/ui-bootstrap/src/wrappers/fieldset.ts
src/ui-bootstrap/src/wrappers/label.ts
src/ui-bootstrap/src/wrappers/message-validation.ts

fixed #460
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/499)

feat: use `ng-template` for dynamic components

---

.travis.yml
src/core/src/services/formly.config.spec.ts
src/core/src/services/formly.config.ts

Fix #502
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/503)

fix(#502): take account of extended wrappers when is not set.

---

demo/src/app.component.ts
src/core/src/services/formly.form.builder.spec.ts
src/core/src/services/formly.form.builder.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/506)

fix(#505): take account of disable option on build.

---

src/core/src/components/formly.field.ts
src/core/src/templates/field.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/507)

feat: remove deprecated options.

---

.config/build.js
.config/publish.js
package.json
src/ui-bootstrap/ng-package.json

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/510)

feat(npm): add publish script

---

package.json

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/520)

feat(npm): allow angular v5.

---

src/core/src/services/formly.form.builder.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/521)

refactor(validator): use min/max functions provided by angular validators.

---

src/ui-bootstrap/src/wrappers/label.ts

fixed #517
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/523)

feat(label): append with an asterisk when required

---

demo/src/formly/index.ts
package.json
src/core/src/components/formly.field.ts
src/core/src/services/formly.config.ts
src/core/src/services/formly.form.builder.spec.ts
src/core/src/services/formly.form.builder.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/524)

fix(#514): avoid supress and/or force validation messages.

---

README.md

My team use the project with angular 4, thanks @JoaoPedro61 for the comment.
**What kind of change does this PR introduce? [Bug fix, feature, docs update]**
**What is the current behavior? Don't work with angular 4**
**What is the new behavior? Work's with angular 4**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/527)

doc:Compatible with angular 4

---

demo/index.html
src/ui-bootstrap/src/types/input.ts
src/ui-bootstrap/src/types/select.ts
src/ui-bootstrap/src/types/textarea.ts
src/ui-bootstrap/src/wrappers/fieldset.ts
src/ui-bootstrap/src/wrappers/message-validation.ts
yarn.lock

Fixed #501
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/529)

feat(bootstrap): support Bootstrap 4 Beta

---

.config/build.js
README.md
package.json
src/core/package.json
src/ui-bootstrap/package.json
src/ui-material/package.json
yarn.lock

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/538)

feat(#536): use standard-version for CHANGELOG generation

---

README.md

Adds a link to the README which points to the guides page which has further examples.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/541)

docs: add link to demo page

---

package.json
src/core/src/components/formly.attributes.spec.ts
src/core/src/components/formly.attributes.ts
src/core/src/components/formly.field.ts
src/core/src/core.module.ts
src/core/src/services/formly.config.ts
src/ui-bootstrap/src/ui-bootstrap.module.ts
yarn.lock

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/545)

added support for Angular version 5 + suggest to use the new package name

---

src/ui-bootstrap/src/ui-bootstrap.config.ts
src/ui-material/src/ui-material.config.ts

fix #544
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/546)

fix(textarea):  set default value for rows and cols

---

CHANGELOG.md
src/core/src/services/formly.form.builder.spec.ts
src/core/src/services/formly.form.builder.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/548)

feat(field): allow passing function for field expression.

---

src/core/src/utils.spec.ts
src/core/src/utils.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/549)

fix(clone): create clone of date instead of empty object.

---

src/core/src/services/formly.form.builder.spec.ts
src/core/src/services/formly.form.builder.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/553)

fix(#551): ensure templateOptions is defined

---

demo/src/app/app.component.ts
src/core/src/utils.spec.ts
src/core/src/utils.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/552)

fix(#551): fixed assign object to string for `assignModelValue`

---

src/core/src/components/formly.field.config.ts
src/core/src/components/formly.form.ts
src/core/src/services/formly.config.ts
src/core/src/services/formly.form.builder.spec.ts
src/core/src/utils.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/557)

fix(#420): allow reset wrappers

---

.angular-cli.json
.travis.yml
package.json
yarn.lock

**What kind of change does this PR introduce? feature, docs update**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/559)

feat(travis): deploy to gh-pages

---

package.json
src/core/src/components/formly.field.config.ts
src/core/src/components/formly.field.ts
src/core/src/components/formly.form.ts
src/core/src/core.module.ts
src/core/src/core.ts
src/core/src/services/formly.form.builder.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/563)

docs(FieldConfig): add a description for properties of the config.

---

.travis.yml
src/core/src/components/formly.field.config.ts
src/core/src/components/formly.field.ts
src/core/src/services/formly.form.builder.ts
tsconfig.json

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/564)

fix(demo): ensure demo is build without error.

---

demo/src/app/app.component.ts
demo/src/app/formly/index.ts
demo/src/app/formly/types/repeatedSection.ts
src/core/src/components/formly.field.config.ts
src/core/src/components/formly.form.spec.ts
src/core/src/components/formly.form.ts
src/core/src/components/formly.group.ts
src/core/src/services/formly.config.spec.ts
src/core/src/services/formly.config.ts
src/core/src/services/formly.form.builder.spec.ts
src/core/src/templates/field.ts
src/core/src/templates/formly.validation-message.spec.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/567)

feat(#566): Show errors on submit

---

demo/src/app/formly/types/repeatedSection.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/568)

feat(demo): simplify `repeat` field type.

---

src/ui-material/package.json

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/570)

feat(material): allow rc versions

---

demo/src/app/app.component.ts
src/core/src/components/formly.field.config.ts
src/core/src/services/formly.config.ts
tslint.json

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/573)

fix(FormlyConfig): allow using function in validation messages.

---

src/core/src/services/formly.config.spec.ts
src/core/src/services/formly.config.ts

**What kind of change does this PR introduce? Bug fix **
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/576)

fix(validation): display errors on blur.

---

package.json
src/core/src/components/formly.field.spec.ts
src/core/src/components/formly.field.ts

fix #580
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/581)

fix(core): take account of model changes when using hideExpression.

---

README.md
demo/src/app/examples/field-options/model-options/model-options.module.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/584)

docs: update README + fixed typo.

---

demo/src/app/shared/copier/copier.service.ts
demo/src/app/shared/example-viewer/example-viewer.component.html
demo/src/app/shared/example-viewer/example-viewer.component.ts
demo/src/app/shared/shared.module.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/585)

feat(demo): add copy to clipboard to example-viewer.

---

src/ui-material/package.json
src/ui-material/src/ui-material.config.ts
src/ui-material/src/wrappers/form-field.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/587)

feat(material): use stable version `5.0.0`

---

demo/src/app/examples/advanced/repeating-section/repeat-section.type.ts
src/core/src/components/formly.field.spec.ts
src/core/src/components/formly.field.ts
src/core/src/components/formly.form.spec.ts
src/core/src/components/formly.form.ts
src/core/src/services/formly.form.builder.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/586)

fix(core): remove usage of setTimeout.

---

demo/src/app/examples/introduction/app.component.html
demo/src/app/examples/introduction/app.component.ts
demo/src/app/examples/introduction/app.module.ts
src/core/src/components/formly.field.ts
src/core/src/components/formly.form.spec.ts
src/core/src/services/formly.form.builder.ts
src/core/src/utils.ts

fix #582
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/590)

fix(core): change form validity when expressionProperty change.

---

src/core/src/components/formly.field.ts
src/core/src/components/formly.form.spec.ts
src/core/src/components/formly.form.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/591)

fix(core): mark form unsubmitted on reset form.

---

demo/src/app/examples/advanced/multi-step-form/app.component.html
demo/src/app/examples/advanced/multi-step-form/app.component.ts
demo/src/app/examples/advanced/multi-step-form/app.module.ts
demo/src/app/examples/advanced/multi-step-form/config.module.ts
demo/src/app/examples/advanced/repeating-section/app.component.html
demo/src/app/examples/bootstrap-formly/select/app.component.html
demo/src/app/examples/bootstrap-formly/table-rows/app.component.html
demo/src/app/examples/bootstrap-specific/advanced-layout/app.component.html
demo/src/app/examples/bootstrap-specific/bootstrap-horizontal/app.component.html
demo/src/app/examples/bootstrap-specific/input-add-ons/app.component.html
demo/src/app/examples/examples.component.ts
demo/src/app/examples/examples.module.ts
demo/src/app/examples/field-options/default-value/app.component.html
demo/src/app/examples/field-options/expression-properties/app.component.html
demo/src/app/examples/field-options/hide-fields/app.component.html
demo/src/app/examples/field-options/model-options/app.component.html
demo/src/app/examples/form-options/form-state/app.component.html
demo/src/app/examples/form-options/reset-model/app.component.html
demo/src/app/examples/introduction/app.component.html
demo/src/app/examples/other/advanced-layout-flex/app.component.html
demo/src/app/examples/other/cascaded-select/app.component.html
demo/src/app/examples/other/disable-submit-button/app.component.html
demo/src/app/examples/other/force-show-error/app.component.html
demo/src/app/examples/other/matching-two-fields/app.component.html
demo/src/app/examples/other/toggle-required/app.component.html
demo/src/app/shared/example-viewer/example-viewer.component.html
demo/src/app/shared/example-viewer/example-viewer.component.ts
demo/src/app/shared/examples-router-viewer/examples-router-viewer.component.ts
demo/src/app/shared/shared.module.ts
ui-bootstrap.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/593)

 demo: add multi-step form example.

---

demo/src/app/examples/advanced/multi-step-form/config.module.ts
demo/src/app/shared/example-viewer/example-viewer.component.scss
src/core/src/components/formly.field.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/594)

refactor(core): remove usage of Renderer2 in formly-field

---

src/core/src/services/formly.form.builder.spec.ts
src/core/src/services/formly.form.builder.ts

**What kind of change does this PR introduce? refactor**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/595)

refactor(core): remove `defaultPath` in FormlyFormBuilder.

---

src/core/src/services/formly.form.builder.spec.ts
src/core/src/services/formly.form.builder.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/596)

fix(core): assign correctly model value in field expression during build.

---

src/core/src/services/formly.form.builder.spec.ts
src/core/src/services/formly.form.builder.ts

related to #596
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/597)

fix(core): ensure nested form group is created for nested key.

---

demo/src/app/examples/bootstrap-formly/select/app.component.ts
src/ui-bootstrap/src/types/select.ts
src/ui-material/src/types/select.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/598)

feat(bootstrap,material): add multi-select support

---

demo/src/app/app.component.html
src/ui-bootstrap/src/types/select.ts

fix #601
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/602)

fix(bootstrap): ensure to set a string value when select is not multiple.

---

src/ui-bootstrap/src/types/multicheckbox.ts
src/ui-bootstrap/src/types/radio.ts
src/ui-material/src/types/multicheckbox.ts

fix #607
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/608)

fix(bootstrap,material): ensure ids is unique for radio and checkbox types.

---

src/ui-bootstrap/src/types/select.ts
src/ui-material/src/types/select.ts

**What kind of change does this PR introduce? Bug fix**\
fix #611
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/612)

fix(select): ensure selectOption is updated when using expression.

---

src/core/src/components/formly.field.config.ts
src/core/src/services/formly.form.builder.spec.ts
src/core/src/services/formly.form.builder.ts

#617
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/618)

fix(validation): assign defaultOptions before validation init.

---

demo/src/app/examples/examples.component.ts
demo/src/app/examples/examples.module.ts
demo/src/app/examples/other/nested-formly-forms/app.component.html
demo/src/app/examples/other/nested-formly-forms/app.component.ts
demo/src/app/examples/other/nested-formly-forms/app.module.ts
demo/src/app/examples/other/nested-formly-forms/config.module.ts
demo/src/app/examples/other/nested-formly-forms/panel-wrapper.component.ts
demo/src/styles.scss

fix #613
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/619)

demo: add Nested Forms example.

---

src/ui-material/src/types/checkbox.ts
src/ui-material/src/types/input.ts
src/ui-material/src/types/radio.ts
src/ui-material/src/types/select.ts
src/ui-material/src/types/textarea.ts
src/ui-material/src/wrappers/form-field.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/622)

fix(material): force setting formly id

---

demo/src/styles.scss
src/ui-bootstrap/src/types/checkbox.ts
src/ui-material/src/types/checkbox.ts

fix #623
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/624)

fix(material,bootstrap): Add asterisk for checkbox.

---

demo/src/app/examples/other/cascaded-select/app.component.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/625)

docs(Cascaded Select): add three level example

---

demo/src/app/examples/examples.component.ts
demo/src/app/examples/examples.module.ts
demo/src/app/examples/other/button/app.component.html
demo/src/app/examples/other/button/app.component.ts
demo/src/app/examples/other/button/app.module.ts
demo/src/app/examples/other/button/button-type.component.ts
demo/src/app/examples/other/button/config.module.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/629)

demo: add button type example.

---

demo/src/app/examples/examples.component.ts
demo/src/app/examples/examples.module.ts
demo/src/app/examples/validation/unique-value-async-validation/app.component.html
demo/src/app/examples/validation/unique-value-async-validation/app.component.ts
demo/src/app/examples/validation/unique-value-async-validation/app.module.ts
demo/src/app/examples/validation/unique-value-async-validation/config.module.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/634)

demo: add Async validation of unique value.

---

karma.conf.js
src/core/src/components/formly.attributes.ts
src/core/src/components/formly.field.ts
src/core/src/components/formly.form.spec.ts
src/core/src/components/formly.form.ts
src/core/src/services/formly.config.ts
src/core/src/services/formly.form.builder.spec.ts
src/core/src/services/formly.form.builder.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/639)

fix(core): take account of hideExpression for fieldGroup with empty key

---

demo/src/app/examples/other/button/button-type.component.ts
src/core/src/components/formly.form.spec.ts
src/core/src/services/formly.form.builder.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/647)

fix(core): wrap hideExpression for field in fieldGroup.

---

src/core/src/components/formly.field.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/650)

fix(core): ensure key is set when toggle `hide`.

---

src/core/src/components/formly.field.config.ts
src/ui-material/src/types/checkbox.ts
src/ui-material/src/types/radio.ts
src/ui-material/src/types/select.ts
src/ui-material/src/ui-material.config.ts

fix #390
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/651)

fix(material): ensure calls to change event.

---

src/ui-material/src/types/checkbox.ts
src/ui-material/src/types/multicheckbox.ts
src/ui-material/src/types/radio.ts

fix #616
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/652)

fix(material): remove underline for radio and checkbox field.

---

demo/src/app/examples/validation/validation-message/app.component.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/653)

demo: add some fixes for validation-message example

---

src/ui-bootstrap/src/ui-bootstrap.config.ts
src/ui-material/src/types/checkbox.ts
src/ui-material/src/types/radio.ts
src/ui-material/src/types/select.ts
src/ui-material/src/ui-material.config.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/655)

fix(bootstrap, material): add default value for select options.

---

demo/src/styles.scss
package.json
src/ui-bootstrap/src/wrappers/addons.ts
yarn.lock

fix #656
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/657)

feat(bootstrap): add missing addons style.

---

demo/src/app/examples/examples.component.ts
demo/src/app/examples/examples.module.ts
demo/src/app/examples/other/json-powered/app.component.html
demo/src/app/examples/other/json-powered/app.component.ts
demo/src/app/examples/other/json-powered/app.module.ts
demo/src/app/examples/other/json-powered/config.module.ts
demo/src/app/examples/other/json-powered/user.service.ts
demo/src/assets/json-powered/user-form.json
demo/src/assets/json-powered/user.json

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/663)

demo: add JSON powered example

---

demo/src/app/examples/other/json-powered/config.module.ts
src/core/src/components/formly.field.ts

fix #658
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/664)

fix(core): take account of model changes in wrappers and types.

---

src/core/src/services/formly.form.builder.spec.ts
src/core/src/services/formly.form.builder.ts

fix #665
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/666)

fix(core): ensure passing a string path for FormGroup.

---

demo/src/app/examples/examples.component.ts
demo/src/app/examples/examples.module.ts
demo/src/app/examples/other/input-file/app.component.html
demo/src/app/examples/other/input-file/app.component.ts
demo/src/app/examples/other/input-file/app.module.ts
demo/src/app/examples/other/input-file/config.module.ts
demo/src/app/examples/other/input-file/file-type.component.ts
demo/src/app/examples/other/input-file/file-value-accessor.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/672)

demo: add file input example.

---

src/ui-bootstrap/src/types/checkbox.ts
src/ui-material/src/types/checkbox.ts

fix #674
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/675)

fix(bootstrap,material): ensure using the model value for indeterminate state check.

---

.travis.yml
package.json
yarn.lock

fix #654
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/676)

chore: add bundlesize check

---

demo/src/app/shared/example-viewer/example-viewer.component.html
demo/src/app/shared/example-viewer/example-viewer.component.ts
package.json
yarn.lock

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/677)

demo: use `json-formatter` for model preview.

---

src/ui-bootstrap/src/types/checkbox.ts
src/ui-bootstrap/src/ui-bootstrap.config.ts
src/ui-material/src/types/checkbox.ts
src/ui-material/src/ui-material.config.ts

fix #674
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/678)

feat(bootstrap, material): allow disable indeterminate state for checkbox.

---

demo/src/assets/json-powered/user-form.json
src/ui-bootstrap/src/types/checkbox.ts
src/ui-bootstrap/src/types/multicheckbox.ts
src/ui-bootstrap/src/types/radio.ts

fix #679
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/682)

fix(bootstrap): add missing bs4 label class for radio and multicheckbox.

---

.config/webpack.test.js
demo/src/tsconfig.app.json
demo/tsconfig.json
package.json
src/core/src/components/formly.attributes.ts
src/core/src/components/formly.field.config.ts
src/core/src/components/formly.field.ts
src/core/src/services/formly.config.ts
src/core/src/services/formly.form.builder.ts
src/core/src/utils.ts
src/ui-bootstrap/src/types/select.ts
src/ui-material/src/types/checkbox.ts
src/ui-material/src/types/input.ts
src/ui-material/src/types/multicheckbox.ts
src/ui-material/src/types/radio.ts
src/ui-material/src/types/select.ts
src/ui-material/src/wrappers/form-field.ts
tsconfig-spec.json
tsconfig.json

fix #691
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/692)

chore: enable noImplicitAny

---

src/core/src/components/formly.field.ts
src/core/src/components/formly.form.ts
src/core/src/core.module.ts
src/core/src/services/formly.form.expression.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/696)

feat(core): add FormlyFormExpression for eval field expressions.

---

src/core/src/components/formly.form.ts
src/core/src/components/formly.group.ts
src/core/src/services/formly.form.builder.spec.ts
src/core/src/services/formly.form.builder.ts
src/core/src/services/formly.form.expression.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/697)

perf(core): avoid build field twice.

---

src/core/src/components/formly.form.ts
src/core/src/services/formly.form.builder.spec.ts
src/core/src/services/formly.form.builder.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/700)

fix(core): check fields expression after build to avoid creation dup formcontrol.

---

demo/src/app/examples/other/cascaded-select/app.component.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/705)

perf: avoid using expressionProperties for Cascaded Select example.

---

src/ui-bootstrap/src/types/input.ts

fix #699
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/706)

fix(bootstrap): fixed input width when using add-ons

---

src/core/src/services/formly.form.expression.spec.ts
src/core/src/services/formly.form.expression.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/709)

fix(core): ensure passing a valid form for checkField when fieldGroup is set.

---

src/core/src/services/formly.form.builder.spec.ts
src/core/src/services/formly.form.builder.ts
src/core/src/services/formly.form.expression.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/712)

perf(core): avoid check fields expression in child component.

---

demo/src/app/examples/other/cascaded-select/app.component.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/714)

demo: use `next` to emit destroy event.

---

demo/src/app/examples/other/cascaded-select/app.component.ts
demo/src/index.html

fix #716
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/717)

fix(demo): add Material+Icons stylesheet

---

demo/src/app/examples/other/input-file/app.component.ts
src/ui-material/src/types/checkbox.ts
src/ui-material/src/types/field.ts
src/ui-material/src/types/input.ts
src/ui-material/src/types/multicheckbox.ts
src/ui-material/src/types/radio.ts
src/ui-material/src/types/select.ts
src/ui-material/src/ui-material.config.ts
src/ui-material/src/wrappers/form-field.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/718)

feat(material): simplify creation custom field type.

---

src/ui-material/src/types/field.ts
src/ui-material/src/types/types.ts
src/ui-material/src/ui-material.ts
src/ui-material/src/wrappers/form-field.ts

fix #715
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/719)

feat(material): allow using matPrefix/matSuffix within form-field wrapper.

---

demo/src/app/examples/advanced/tabs/app.component.html
demo/src/app/examples/advanced/tabs/app.component.ts
demo/src/app/examples/advanced/tabs/app.module.ts
demo/src/app/examples/advanced/tabs/config.module.ts
demo/src/app/examples/examples.component.ts
demo/src/app/examples/examples.module.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/722)

demo: add Tabs integration example.

---

src/core/src/components/formly.form.spec.ts
src/core/src/services/formly.form.expression.ts

fix #723
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/724)

fix(core): assign changed model in expressionProperties into formControl.

---

demo/src/app/shared/example-viewer/example-viewer.component.ts
src/core/src/services/formly.form.expression.ts
src/ui-material/src/types/select.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/725)

perf(core): use JSON.stringify for comparing object in expressionProperties.

---

src/core/src/components/formly.form.spec.ts
src/core/src/components/formly.form.ts
src/core/src/services/formly.form.expression.ts

fix #720
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/726)

feat(core): add `modelChange` output to emit the formly model changes.

---

src/core/src/components/formly.group.ts
src/core/src/core.module.ts
src/core/src/services/formly.config.ts
src/core/src/services/formly.form.builder.spec.ts
src/core/src/services/formly.form.builder.ts
src/core/src/services/formly.form.expression.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/727)

refactor(core): move 'formly-group' declaration into FormlyModule.

---

src/core/src/components/formly.form.spec.ts
src/core/src/components/formly.form.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/728)

fix(core): ensure emitting modelChange for nested field groups.

---

src/ui-bootstrap/src/types/input.ts

fix #729
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/730)

fix(bootstrap): ensure emitting an int value for number input type.

---

src/core/src/components/formly.attributes.ts

fix #732
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/733)

feat(core): add support for readonly property.

---

src/core/src/services/formly.form.builder.spec.ts
src/core/src/services/formly.form.builder.ts

fix #729
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/740)

fix(core): ignore built-in validations only when passing false value.

---

src/ui-bootstrap/src/types/checkbox.ts
src/ui-bootstrap/src/wrappers/label.ts
src/ui-material/src/types/checkbox.ts
src/ui-material/src/wrappers/form-field.ts

fix #738
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/741)

feat(bootstrap, material): allow removing the required asterisk symbol.

---

src/ui-bootstrap/src/types/select.ts

fix #739
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/742)

fix(bootstrap): avoid displaying blank field in select.

---

src/core/src/services/formly.form.expression.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/743)

fix(FormlyFormExpression): ensure ParentFormControl is set when for check field visibility.

---

src/core/src/components/formly.field.config.ts
src/core/src/components/formly.form.spec.ts
src/core/src/components/formly.form.ts
src/core/src/services/formly.config.ts
src/core/src/services/formly.form.builder.ts
src/core/src/services/formly.form.expression.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/748)

feat(formly-form): allow passing FormArray in form input.

---

demo/src/app/examples/advanced/repeating-section/repeat-section.type.ts
src/core/src/core.ts
src/core/src/templates/field-array.type.ts
src/core/src/utils.ts

[Repeating Section](https://formly-js.github.io/ngx-formly/examples/advanced/repeating-section) example has been updated, we higly recomand to update your code if you use
`RepeatTypeComponent` in order to take advantage of that new feature.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/749)

feat(core): introduce FieldArrayType to simplify managing repeating fields.

---

src/core/src/components/formly.form.spec.ts
src/core/src/components/formly.form.ts
src/core/src/templates/field-array.type.ts
src/core/src/utils.ts

fix #648
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/750)

fix(core): reset FormArray when resetting model.

---

src/core/src/components/formly.form.ts
src/core/src/services/formly.form.builder.spec.ts
src/core/src/services/formly.form.builder.ts
src/core/src/templates/field-array.type.ts
src/core/src/utils.spec.ts
src/core/src/utils.ts

fix #745
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/751)

fix(core): rely on `__build__` to check expression instead of parentFormlyForm.

---

demo/src/app/shared/example-viewer/example-viewer.component.html
demo/src/app/shared/example-viewer/example-viewer.component.ts

fix #754
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/755)

fix(demo): take account of model changes in example-viewer.

---

src/ui-bootstrap/src/run/validation.ts

fix #757
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/759)

fix(bootstrap): show error message when asyncValidators is set.

---

src/core/src/services/formly.form.builder.spec.ts
src/core/src/services/formly.form.builder.ts

fix #761
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/762)

fix(core): set empty array as defaultValue when fieldArray is set.

---

src/core/src/utils.spec.ts
src/core/src/utils.ts

fix #763
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/766)

fix(core): take account of RegExp in clone.

---

demo/src/app/shared/example-viewer/example-viewer.component.ts
src/core/src/components/formly.form.spec.ts
src/ui-bootstrap/src/types/select.spec.ts
src/ui-material/src/types/select.spec.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/776)

test(material): add test for select with observables

---

src/core/src/components/formly.form.ts
src/core/src/services/formly.config.spec.ts
src/core/src/services/formly.form.builder.spec.ts
src/core/src/services/formly.form.builder.ts

fix #774
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/779)

fix(core): ensure options is initialized during build.

---

src/core/src/components/formly.form.ts

fix #781
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/783)

fix(core): avoid reset parent form when resetting model.

---

README.md
demo/src/app/examples/other/observable-select/app.component.ts
src/core/src/services/formly.form.builder.spec.ts
src/core/src/services/formly.form.builder.ts

fix #782
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/784)

fix(core): take account of model changes for an existent field form.

---

src/core/src/components/formly.form.ts

fix #785
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/786)

fix(core): change `submitted` state on resetForm.

---

src/core/src/components/formly.form.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/787)

fix(core): take account of model changes when fields is already builded.

---

src/core/src/components/formly.form.spec.ts
src/core/src/components/formly.form.ts

fix #788
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/789)

fix(core): rebuild fields when `form` change.

---

demo/src/app/examples/bootstrap-specific/bootstrap-horizontal/app.component.ts
demo/src/app/examples/bootstrap-specific/bootstrap-horizontal/app.module.ts
demo/src/app/examples/bootstrap-specific/bootstrap-horizontal/horizontal-wrapper.ts

**What kind of change does this PR introduce? demo update**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/792)

demo: improve bootstrap horizontal example.

---

demo/src/app/guides/custom-formly-field.md
demo/src/app/guides/guides.component.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/795)

docs(guides): add how to create custom form field.

---

src/core/src/components/formly.form.ts
src/core/src/services/formly.form.builder.spec.ts
src/core/src/services/formly.form.builder.ts

fix #794
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/797)

fix(core): use patch method instead of reset when model change.

---

README.md
demo/src/app/examples/advanced/multi-step-form/app.component.html
demo/src/app/examples/advanced/multi-step-form/app.component.ts
demo/src/app/examples/advanced/tabs/app.component.html
demo/src/app/examples/advanced/tabs/app.component.ts
demo/src/app/examples/advanced/tabs/config.module.ts
src/core/src/components/formly.form.ts

fix #796
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/798)

fix(core): call the `parentForm.reset` only if it match the current form.

---

src/core/src/components/formly.form.spec.ts
src/core/src/components/formly.form.ts

fix #801
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/803)

fix(core): avoid calling checkExpressionChange and buildForm in FormlyGroup.

---

src/core/src/components/formly.field.spec.ts
src/core/src/components/formly.field.ts
src/core/src/components/formly.form.spec.ts
src/core/src/components/formly.form.ts
src/core/src/components/formly.group.ts
src/core/src/services/formly.form.builder.spec.ts
src/core/src/services/formly.form.builder.ts
src/core/src/services/formly.form.expression.ts

fix #805
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/809)

fix(core): move tracking model change to root component.

---

src/core/src/services/formly.form.builder.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/810)

perf(core): avoid calling setControl if control already exist in form.

---

src/core/src/components/formly.form.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/811)

perf(core): check field expression only in root component.

---

src/core/src/components/formly.form.spec.ts
src/core/src/components/formly.form.ts

fix #805
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/812)

fix(core): fallback to null for an non-existing member on model change.

---

demo/src/app/guides/guides.component.ts
demo/src/app/guides/properties-options.md
demo/src/styles.scss

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/819)

docs(guides): add Properties and Options.

---

src/core/src/components/formly.form.spec.ts
src/core/src/components/formly.form.ts
src/core/src/templates/field-array.type.ts

fix #821 #822
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/823)

fix(core): ensure tracking model changes when using Repeating section.

---

demo/src/app/home/home.component.html

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/824)

docs: fixed typo.

---

src/ui-bootstrap/src/run/description.ts
src/ui-bootstrap/src/run/validation.ts
src/ui-bootstrap/src/wrappers/description.ts
src/ui-bootstrap/src/wrappers/message-validation.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/826)

fix(bootstrap): always enable description + validation for templateManipulators.

---

src/core/src/components/formly.form.ts

fix #827
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/829)

fix(core): subscribe to formcontrol when key and type are set.

---

src/core/src/components/formly.form.spec.ts
src/core/src/services/formly.form.expression.ts

fix #832
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/833)

fix(core): allow passing falsy value for hideExpression.

---

src/core/src/components/formly.attributes.spec.ts
src/core/src/components/formly.attributes.ts

fix #760
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/835)

fix(core): remove aria-describedby

---

demo/src/app/guides/expresion-properties.md
demo/src/app/guides/guides.component.ts
demo/src/app/guides/validation.md
src/core/src/utils.ts

Thanks to @Pat-Lovelace and @davidoween
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/836)

feat(docs): add validation + expression-properties section.

---

demo/src/app/examples/examples.component.ts
demo/src/app/guides/guides.component.ts
demo/src/index.html
demo/src/markdown.css
demo/src/styles.scss

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/837)

docs: use github markdown theme.

---

CHANGELOG.md
src/core/src/components/formly.form.spec.ts
src/core/src/services/formly.form.builder.ts
src/core/src/services/formly.form.expression.ts

fix #844
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/847)

fix(core): apply disabled status to child field when fieldGroup is set.

---

src/core/src/services/formly.form.builder.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/852)

fix(core): remove hide field to force re-evalute it in FormlyFormExpression.

---

src/core/src/components/formly.attributes.ts
src/core/src/components/formly.field.config.ts
src/ui-material/src/types/checkbox.ts
src/ui-material/src/types/radio.ts
src/ui-material/src/types/select.ts

fix #867
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/870)

feat(core): pass event instead of formControl to FormlyAttributes events.

---

src/core/src/components/formly.field.spec.ts
src/core/src/components/formly.field.ts
src/core/src/templates/field.type.ts
src/ui-material/src/types/checkbox.ts
src/ui-material/src/types/field.ts
src/ui-material/src/types/multicheckbox.ts
src/ui-material/src/types/radio.ts

fix #643
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/872)

feat(core): move managing lifeCycle hooks to `formly-field` component

---

src/core/src/components/formly.form.spec.ts
src/core/src/components/formly.form.ts

fix #881
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/883)

fix(core): take account of hidden fields when reseting model.

---

.github/ISSUE_TEMPLATE.md
README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/885)

style: add stackblitz starter example.

---

.config/build.js
.config/publish.js
README.md
commitlint.config.js
package.json
src/ui-ionic/src/types/input.ts
src/ui-ionic/src/types/radio.ts
src/ui-material/src/ui-material.config.ts
src/ui-material/src/wrappers/form-field.ts
src/ui-primeng/index.ts
src/ui-primeng/ng-package.json
src/ui-primeng/package.json
src/ui-primeng/public_api.ts
src/ui-primeng/src/types/checkbox.ts
src/ui-primeng/src/types/input.ts
src/ui-primeng/src/types/radio.ts
src/ui-primeng/src/types/select.ts
src/ui-primeng/src/types/textarea.ts
src/ui-primeng/src/types/types.ts
src/ui-primeng/src/ui-primeng.config.ts
src/ui-primeng/src/ui-primeng.module.ts
src/ui-primeng/src/ui-primeng.ts
src/ui-primeng/src/wrappers/form-field.ts
src/ui-primeng/src/wrappers/wrappers.ts
yarn.lock

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/887)

feat: initial work for primeng support

---

src/core/src/templates/field-array.type.ts

fix #890
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/894)

fix(core): do not force using FormGroup when FieldArray is set.

---

demo/src/app/ui/ui-ionic/app.component.scss
demo/src/app/ui/ui-ionic/config.module.ts
demo/src/app/ui/ui-ionic/datetime/app.component.html
demo/src/app/ui/ui-ionic/datetime/app.component.ts
demo/src/app/ui/ui-ionic/datetime/app.module.ts
demo/src/app/ui/ui-ionic/datetime/index.ts
demo/src/app/ui/ui-ionic/range/app.component.html
demo/src/app/ui/ui-ionic/range/app.component.ts
demo/src/app/ui/ui-ionic/range/app.module.ts
demo/src/app/ui/ui-ionic/range/index.ts
demo/src/app/ui/ui-ionic/toggle/app.component.html
demo/src/app/ui/ui-ionic/toggle/app.component.ts
demo/src/app/ui/ui-ionic/toggle/app.module.ts
demo/src/app/ui/ui-ionic/toggle/index.ts
demo/src/app/ui/ui-material/config.module.ts
demo/src/app/ui/ui-material/datepicker/app.component.html
demo/src/app/ui/ui-material/datepicker/app.component.ts
demo/src/app/ui/ui-material/datepicker/app.module.ts
demo/src/app/ui/ui-material/datepicker/index.ts
src/ui-material/datepicker/src/datepicker.module.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/901)

docs(demo): add missing ui examples

---

README.md
demo/src/app/app.component.html
demo/src/app/app.component.ts
demo/src/app/examples/examples.component.ts
demo/src/app/guides/custom-formly-field.md
demo/src/app/guides/guides.component.ts
demo/src/app/shared/example-viewer/example-viewer.component.html
demo/src/app/shared/example-viewer/example-viewer.component.ts
demo/src/app/shared/examples-router-viewer/examples-router-viewer.component.ts
demo/src/app/shared/stackblitz/stackblitz-button.ts
demo/src/app/shared/stackblitz/stackblitz-writer.ts
demo/src/app/ui/ui.component.ts
demo/src/assets/stackblitz/bootstrap/index.html
demo/src/styles.scss
src/ui-material/datepicker/index.ts
src/ui-material/datepicker/src/index.ts
src/ui-material/datepicker/src/public_api.ts
src/ui-material/ng-package.json
src/ui-material/slider/index.ts
src/ui-material/slider/src/index.ts
src/ui-material/slider/src/public_api.ts
src/ui-material/toggle/index.ts
src/ui-material/toggle/src/index.ts
src/ui-material/toggle/src/public_api.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/904)

several fixes in demo and mat lib

---

README.md
demo/src/app/ui/common/index.ts
demo/src/app/ui/ui-bootstrap/config.module.ts
demo/src/app/ui/ui-ionic/config.module.ts
demo/src/app/ui/ui-kendo/config.module.ts
demo/src/app/ui/ui-material/config.module.ts
demo/src/app/ui/ui-primeng/config.module.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/908)

docs(demo): ui add components in entrycomponents

---

src/core/src/services/formly.form.builder.spec.ts
src/core/src/services/formly.form.builder.ts

fix(core): allow using validation with custom validator

---

src/core/src/components/formly.field.spec.ts
src/core/src/components/formly.field.ts
src/core/src/services/formly.form.builder.spec.ts
src/core/src/services/formly.form.builder.ts

fix(core): move building pre/post wrapper into FormBuilder

---

src/core/src/lib/core.ts

fix(core): export FormlyTemplateOptions

---

src/bootstrap/src/lib/bootstrap.module.ts
src/bootstrap/src/lib/select-options.pipe.spec.ts
src/bootstrap/src/lib/select-options.pipe.ts
src/bootstrap/src/lib/types/select.spec.ts
src/bootstrap/src/lib/types/select.ts
src/material/src/lib/select-options.pipe.spec.ts
src/material/src/lib/select-options.pipe.ts
src/material/src/lib/types/select.spec.ts
src/material/src/lib/types/select.ts
src/material/src/lib/ui-material.module.ts

feat: add grouped select support when binding observables

---

src/material/datepicker/src/datepicker.type.ts
src/material/slider/src/slider.type.ts
src/material/src/lib/types/checkbox.ts
src/material/src/lib/types/multicheckbox.ts
src/material/src/lib/types/radio.ts
src/material/src/lib/wrappers/form-field.ts

feat(material): allow setting custom appearance and color

---

src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/components/formly.form.ts

fix(core): ensure tracking model change after reseting model

---

src/core/src/lib/services/formly.form.builder.ts
src/material/form-field/src/form-field.wrapper.ts

fix(material): recalculate the gap size after displaying field

---

src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/components/formly.form.ts

fix(core): update field model when assigning a new model

---

src/core/src/lib/services/formly.form.expression.spec.ts
src/core/src/lib/services/formly.form.expression.ts

fix(core): avoid passing a number path when handling hideExpression

---

demo/src/app/examples/validation/matching-two-fields/app.component.ts

docs(demo): improve matching two fields example

---

src/bootstrap/src/lib/run/description.ts
src/bootstrap/src/lib/run/validation.ts

fix(bootstrap): allow disabling the default templateManipulator wrappers

---

src/core/src/lib/utils.ts

refactor(core): simplify eval string expression

---

src/material/select/src/select-options.pipe.spec.ts
src/material/select/src/select-options.pipe.ts
src/material/select/src/select.type.ts

feat(material): allow passing function for labelProp and valueProp

---

src/core/src/lib/services/formly.form.builder.spec.ts
src/core/src/lib/services/formly.form.builder.ts

fix(core): ensure passing a valid model for FormGroup instance

---

src/core/src/lib/components/formly.field.config.ts
src/core/src/lib/utils.spec.ts
src/core/src/lib/utils.ts

feat(core): add access to the parent field from children

---

src/bootstrap/package.json
src/bootstrap/src/lib/types/checkbox.ts
src/bootstrap/src/lib/types/input.ts
src/bootstrap/src/lib/types/multicheckbox.ts
src/bootstrap/src/lib/types/radio.ts
src/bootstrap/src/lib/wrappers/addons.ts
src/bootstrap/src/lib/wrappers/description.ts
src/bootstrap/src/lib/wrappers/label.ts
src/bootstrap/src/lib/wrappers/message-validation.ts

feat(bootstrap): remove bootstrap v3 support

---

src/core/src/lib/services/formly.form.builder.ts
src/core/src/lib/utils.spec.ts
src/core/src/lib/utils.ts

allow passing fieldGroup in defaultOptions

---

src/core/src/lib/services/formly.form.builder.ts
src/core/src/lib/services/formly.form.expression.ts

refactor(core): move init expressions to FormlyFormExpression

---

src/core/src/lib/components/formly.field.config.ts
src/core/src/lib/components/formly.field.spec.ts
src/core/src/lib/components/formly.field.ts
src/core/src/lib/services/formly.form.builder.spec.ts
src/core/src/lib/services/formly.form.builder.ts
src/core/src/lib/services/formly.form.expression.spec.ts
src/core/src/lib/services/formly.form.expression.ts
src/core/src/lib/utils.ts

feat(core): allow passing observable in expressionProperties

---

demo/src/app/shared/stackblitz/stackblitz-button.ts
demo/src/app/ui/ui-material/autocomplete/autocomplete-type.component.ts

fix(demo): fixed material autocomplete stackblitz example

---

src/core/select/src/select-options.pipe.ts

fix(core): allow false value for legacy select-option

---

src/core/src/lib/components/formly.field.ts
src/core/src/lib/core.module.ts
src/core/src/lib/services/formly.config.spec.ts
src/core/src/lib/services/formly.config.ts
src/core/src/lib/services/formly.form.builder.spec.ts
src/core/src/lib/services/formly.form.builder.ts
src/core/src/lib/services/formly.form.expression.spec.ts
src/core/src/lib/services/formly.form.expression.ts

feat(core): use the new providedIn with better lazyload support

---

src/core/src/lib/services/formly.form.builder.spec.ts
src/core/src/lib/services/formly.form.builder.ts

fix(core): update formcontrol validators when fields change

---

demo/src/app/examples/advanced/repeating-section/repeat-section.type.ts
src/core/src/lib/templates/field-array.type.ts

feat(core): add reset action in FieldArrayType

---

src/core/src/lib/services/formly.form.builder.ts

fix(core): apply init fields type for fieldArray

---

demo/src/app/examples/advanced/datatable-integration/app.component.ts
demo/src/app/examples/advanced/datatable-integration/datatable.type.ts

docs(demo): make columns configurable for ngx-datatable

---

.config/build.js
src/schematics/src/ng-add/index.ts
src/schematics/src/ng-add/schema.json

feat(schematics): add nativescript

---

demo/src/app/examples/introduction/app.module.ts
demo/src/app/examples/other/button/app.module.ts
demo/src/app/guides/custom-formly-wrapper.md
src/bootstrap/src/lib/bootstrap.config.ts
src/bootstrap/src/lib/run/description.ts
src/bootstrap/src/lib/run/validation.ts
src/bootstrap/src/lib/types/checkbox.ts
src/bootstrap/src/lib/types/textarea.ts
src/bootstrap/src/lib/wrappers/form-field.wrapper.ts
src/bootstrap/src/lib/wrappers/wrappers.ts
src/core/src/lib/components/formly.attributes.ts
src/material/textarea/src/textarea.type.ts

feat(bootstrap): add form-field wrapper

---

demo/src/app/examples/introduction/app.module.ts
demo/src/app/examples/other/button/app.module.ts
demo/src/app/guides/custom-formly-wrapper.md
src/bootstrap/src/lib/bootstrap.config.ts
src/bootstrap/src/lib/run/description.ts
src/bootstrap/src/lib/run/fieldset.ts
src/bootstrap/src/lib/run/validation.ts
src/bootstrap/src/lib/types/textarea.ts
src/bootstrap/src/lib/wrappers/form-field.wrapper.ts
src/bootstrap/src/lib/wrappers/wrappers.ts
src/core/src/lib/services/formly.config.ts
src/core/src/lib/services/formly.form.builder.ts
src/material/input/src/textarea.type.ts

 feat(bootstrap): deprecate all wrappers in favor of `form-field`

---

demo/src/app/examples/advanced/repeating-section/repeat-section.type.ts
src/core/src/lib/templates/field-array.type.ts

This reverts commit c553ca39f27f06af751dc6f51c2bde88e89e7c79.

Revert "feat(core): add reset action in FieldArrayType"

---

demo/src/app/examples/advanced/json-schema/arrays/array.type.ts
demo/src/app/examples/advanced/json-schema/nested/array.type.ts
demo/src/app/examples/advanced/json-schema/numbers/array.type.ts
demo/src/app/examples/advanced/json-schema/simple/array.type.ts
src/core/src/lib/services/formly.form.builder.ts

fix(core): ensure init fieldArray even if fieldGroup is not set

---

src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/components/formly.form.ts
src/core/src/lib/services/formly.form.builder.ts
src/core/src/lib/services/formly.form.expression.spec.ts
src/core/src/lib/services/formly.form.expression.ts

feat(core): apply disabled status to fieldGroup items

---

demo/src/app/shared/example-viewer/example-viewer.component.html
demo/src/app/shared/example-viewer/example-viewer.component.ts
demo/src/app/shared/examples-router-viewer/examples-router-viewer.component.ts
demo/src/app/shared/shared.module.ts
demo/src/app/ui/common/checkbox/index.ts
demo/src/app/ui/common/index.ts
demo/src/app/ui/common/input/index.ts
demo/src/app/ui/common/radio/index.ts
demo/src/app/ui/common/select/index.ts
demo/src/app/ui/common/textarea/index.ts
demo/src/app/ui/ui-bootstrap/config.module.ts
demo/src/app/ui/ui-ionic/config.module.ts
demo/src/app/ui/ui-ionic/datetime/index.ts
demo/src/app/ui/ui-ionic/range/index.ts
demo/src/app/ui/ui-ionic/toggle/index.ts
demo/src/app/ui/ui-kendo/config.module.ts
demo/src/app/ui/ui-material/autocomplete/index.ts
demo/src/app/ui/ui-material/config.module.ts
demo/src/app/ui/ui-material/datepicker/index.ts
demo/src/app/ui/ui-material/slider/index.ts
demo/src/app/ui/ui-material/toggle/index.ts
demo/src/app/ui/ui-primeng/config.module.ts
src/core/src/lib/core.module.ts
src/core/src/lib/utils.ts
src/material/form-field/src/form-field.wrapper.ts

docs(demo): add debug toolbar in ui examples

---

src/ionic/src/lib/types/checkbox.ts
src/ionic/src/lib/types/datetime.ts
src/ionic/src/lib/types/select.ts
src/ionic/src/lib/types/textarea.ts
src/ionic/src/lib/types/toggle.ts

feat(ionic): allow customize label position

---

.travis.yml
src/bootstrap/src/lib/types/select.ts

fix(bootstrap): ensure using angular multi-select selector

---

src/core/src/lib/components/formly.field.ts

feat(core): rerender field type on change

---

src/bootstrap/src/lib/types/select.ts

feat(bootstrap): add customSelect option to select type

---

src/core/src/lib/services/formly.form.builder.ts

fix(core): page flicker on fieldArray changes

---

src/core/src/lib/components/formly.form.ts
src/core/src/lib/services/formly.form.builder.ts
src/core/src/lib/services/formly.form.expression.ts
src/core/src/lib/utils.ts

feat: fieldArray make key optional + allow passing FormGroup

---

src/core/src/lib/core.ts
src/core/src/lib/services/formly.config.ts
src/core/src/lib/services/formly.form.builder.spec.ts
src/core/src/lib/services/formly.form.builder.ts

feat(core): allow modify field during build-form

---

src/core/src/lib/components/formly.field.config.ts
src/core/src/lib/components/formly.form.ts
src/core/src/lib/extensions/field-expression/field-expression.spec.ts
src/core/src/lib/extensions/field-expression/field-expression.ts
src/core/src/lib/extensions/field-expression/utils.spec.ts
src/core/src/lib/extensions/field-expression/utils.ts
src/core/src/lib/extensions/index.ts
src/core/src/lib/services/formly.config.ts
src/core/src/lib/services/formly.form.builder.spec.ts
src/core/src/lib/services/formly.form.builder.ts
src/core/src/lib/templates/field-array.type.ts
src/core/src/lib/utils.spec.ts
src/core/src/lib/utils.ts

feat(core): introduce field-expression extension

---

demo/src/app/examples/validation/custom-validation/app.component.ts
demo/src/app/examples/validation/custom-validation/app.module.ts
demo/src/app/examples/validation/validation-message/app.component.ts
src/core/src/lib/components/formly.field.config.ts
src/core/src/lib/components/formly.field.ts
src/core/src/lib/services/formly.config.ts
src/core/src/lib/services/formly.form.builder.spec.ts
src/core/src/lib/services/formly.form.builder.ts
src/material/datepicker/src/datepicker.type.ts
src/material/slider/src/slider.type.ts
src/material/toggle/src/toggle.type.ts

small fixes + make all custom-validators optional in demo app

---

src/core/src/lib/components/formly.attributes.spec.ts
src/core/src/lib/components/formly.attributes.ts

feat(core): take account of templateOptions attributes changes

---

src/bootstrap/src/lib/types/checkbox.ts
src/material/checkbox/src/checkbox.type.ts

fix(bootstrap): rely on control value for indeterminate checkbox state

---

src/bootstrap/src/lib/types/radio.ts

fix(bootstrap): get correct radio value through queryselector

---

UPGRADE-5.0.md
package-lock.json
package.json
src/core/src/lib/components/formly.field.ts
src/core/src/lib/components/formly.form.ts

fix(core): take account of deprecated FormlyField inputs changes

---

src/core/src/lib/utils.ts

fix(core): ignore clone SafeHtmlImpl value

---

src/ionic/src/lib/types/input.ts
src/ionic/src/lib/types/textarea.ts

feat(ionic): support textarea rows & cols options

---

src/material/input/src/input.type.ts
src/material/input/src/textarea.type.ts

fix(material): use readonly input instead of formly-attributes

---

src/core/src/lib/components/formly.attributes.spec.ts
src/core/src/lib/components/formly.attributes.ts

fix(material): fallback to default tabindex value

---

.config/build.js
src/bootstrap/package.json
src/core/package.json
src/ionic/package.json
src/kendo/package.json
src/material/package.json
src/nativescript/package.json
src/primeng/package.json
src/schematics/package.json

chore(core): make packages semver compatible

---

src/core/src/lib/core.module.ts

fix(core): add FormlyFormBuilder to child module

---

demo/src/app/ui/ui-material/autocomplete/autocomplete-type.component.ts

docs: rely on formly formField for mat autocomplete example

---

src/core/src/lib/core.ts

feat(core): export FORMLY_CONFIG

---

src/core/src/lib/extensions/field-validation/field-validation.ts

fix(core): display async validation message for OnPush CD

---

src/core/src/lib/components/formly.attributes.spec.ts
src/core/src/lib/components/formly.attributes.ts
src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/extensions/field-validation/field-validation.ts
src/core/src/lib/utils.ts

fix(core): improve managing focus with expressionProperties

---

src/core/src/lib/components/formly.form.ts

feat(core): add support for immutable mode

---

src/core/src/lib/extensions/field-form/field-form.ts
src/core/src/lib/services/formly.form.builder.spec.ts

fix(core): assign a valid value for nested key model

---

src/core/src/lib/components/formly.attributes.ts
src/ionic/src/lib/formly.attributes.ts
src/ionic/src/lib/types/checkbox.ts
src/ionic/src/lib/types/datetime.ts
src/ionic/src/lib/types/field.type.ts
src/ionic/src/lib/types/input.ts
src/ionic/src/lib/types/radio.ts
src/ionic/src/lib/types/range.ts
src/ionic/src/lib/types/select.ts
src/ionic/src/lib/types/textarea.ts
src/ionic/src/lib/types/toggle.ts
src/ionic/src/lib/ui-ionic.module.ts

fix(ionic): user setFocus instead of native focus callback

---

src/core/src/lib/extensions/field-expression/field-expression.spec.ts
src/core/src/lib/extensions/field-expression/field-expression.ts

fix(core): avoid override hide field within fieldGroup

---

src/core/src/lib/extensions/field-form/field-form.ts
src/core/src/lib/services/formly.form.builder.spec.ts

fix(core): avoid init model during addFormControl

---

demo/src/app/examples/advanced/repeating-section-input/app.component.html
demo/src/app/examples/advanced/repeating-section-input/app.component.ts
demo/src/app/examples/advanced/repeating-section-input/app.module.ts
demo/src/app/examples/advanced/repeating-section-input/config.module.ts
demo/src/app/examples/advanced/repeating-section-input/repeat-section.type.ts
demo/src/app/examples/advanced/repeating-section/app.component.ts
demo/src/app/examples/examples.component.ts
demo/src/app/examples/examples.module.ts

docs(demo): add 'repeating-section-with-length-input' example

---

src/core/src/lib/utils.spec.ts
src/core/src/lib/utils.ts

fix(core): reset fields of fieldArray on model change

---

src/core/src/lib/extensions/field-form/field-form.ts
src/core/src/lib/extensions/field-form/utils.ts
src/core/src/lib/templates/field-array.type.ts
src/core/src/lib/utils.ts

fix(core): improve performance for FieldArrayType

---

demo/src/app/app.component.html

docs: move toolbar to the root element

---

src/core/src/lib/extensions/field-form/utils.spec.ts
src/core/src/lib/extensions/field-form/utils.ts

fix(core): disable control when parent is disabled

---

src/material/form-field/src/field.type.ts

fix(material): take account of formFieldControl changes

---

src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/components/formly.form.ts

fix(core): fallback `null` fields to empty array

---

src/bootstrap/src/lib/bootstrap.module.ts
src/ionic/src/lib/ui-ionic.module.ts
src/kendo/src/lib/ui-kendo.module.ts
src/primeng/src/lib/ui-primeng.module.ts

fix: avoid using forRoot for UI

---

demo/src/app/app.component.ts
demo/src/app/examples/advanced/grid-integration/app.component.html
demo/src/app/examples/advanced/grid-integration/app.component.ts
demo/src/app/examples/advanced/grid-integration/app.module.ts
demo/src/app/examples/advanced/grid-integration/config.module.ts
demo/src/app/examples/advanced/grid-integration/grid-formly-cell.component.ts
demo/src/app/examples/advanced/grid-integration/grid.type.ts
demo/src/app/examples/examples.module.ts
demo/src/app/shared/stackblitz/stackblitz-writer.ts
demo/src/styles.scss
package-lock.json
package.json

Feature
Adds a new demo: ag-grid
Adds stackblitz dependencies for this ag-grid demo and for ngx-datatable demo

docs(demo): add example of ag-grid integration

---

src/core/src/lib/extensions/field-validation/field-validation.ts

fix(core): allow passing a non array to the validation property

---

src/core/src/lib/components/formly.attributes.spec.ts
src/core/src/lib/components/formly.attributes.ts

fix(core): remove readonly when passing falsy value

---

src/core/src/lib/extensions/field-validation/field-validation.ts
src/core/src/lib/services/formly.form.builder.spec.ts

fix(core): avoid overriding validators from directive

---

src/core/src/lib/utils.spec.ts
src/core/src/lib/utils.ts

fix(core): assign a valid model for array index key

---

src/kendo/src/lib/types/select.ts
src/primeng/src/lib/types/checkbox.ts
src/primeng/src/lib/types/select.ts

fix: add missing change event for primeng & kendo

---

src/core/src/lib/components/formly.attributes.spec.ts
src/core/src/lib/components/formly.attributes.ts

fix(core): add missing disabled & required html attribute

---

src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/components/formly.form.ts

fix(core): avoid rerender on model change with immutable mode

---

src/material/select/src/select.spec.ts
src/material/select/src/select.type.ts

fix when passing an observable input to the multi-select

fix(material): multi-select when passing observable data

---

src/material/radio/src/radio.type.ts

fix(material): avoid handling focus for selected radio option

---

src/material/checkbox/src/checkbox.type.ts
src/material/radio/src/radio.type.ts
src/primeng/src/lib/types/checkbox.ts

fix(material): remove duplicated change event listener

---

src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/services/formly.config.ts

fix(core): restore support component-level injectors for types

---

src/bootstrap/src/lib/types/select.ts

fix(bootstrap): select empty option when value is null

---

src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/components/formly.form.ts
src/core/src/lib/services/formly.config.ts

feat(core): allow check expression on model changes only

---

src/material/textarea/src/textarea.type.ts

feat(material): add textarea autosize

---

demo/src/app/app.component.ts
demo/src/app/examples/advanced/i18n-alternative/app.component.html
demo/src/app/examples/advanced/i18n-alternative/app.component.ts
demo/src/app/examples/advanced/i18n-alternative/app.module.ts
demo/src/app/examples/advanced/i18n-alternative/assets/en_json
demo/src/app/examples/advanced/i18n-alternative/assets/fr_json
demo/src/app/examples/advanced/i18n-alternative/config.module.ts
demo/src/app/examples/advanced/i18n-alternative/translate.extension.ts
demo/src/app/examples/examples.module.ts

Docs for using an extension for ngx-translate.

docs: add alternative approach for ngx-translate

---

src/core/src/lib/components/formly.field.ts

fix(core): add warn for missing static flag for @ViewChild

---

src/core/src/lib/extensions/field-form/field-form.spec.ts
src/core/src/lib/extensions/field-form/field-form.ts

fix(core): override existing form group instance on re-build

---

src/core/src/lib/utils.spec.ts
src/core/src/lib/utils.ts

fix(core): avoid assigning defaultValue by reference

---

src/core/src/lib/components/formly.field.ts
src/core/src/lib/templates/field.wrapper.ts

feat(core): add support of ivy

---

src/material/checkbox/src/checkbox.type.ts
src/material/form-field/src/form-field.wrapper.ts
src/material/multicheckbox/src/multicheckbox.type.ts

fix(material): improve handling focus for custom form-field

---

.config/deploy.js
src/material/textarea/src/textarea.type.ts

fix(material): float textarea label when value is set

---

src/material/select/src/select.type.ts

fix(material): disable floating label when select value is empty

---

src/core/src/lib/components/formly.form.ts
src/core/src/lib/extensions/field-form/field-form.spec.ts
src/core/src/lib/extensions/field-form/field-form.ts
src/core/src/lib/services/formly.form.builder.spec.ts

feat(core): generate FormControl when `key` is set

---

demo/src/app/examples/bootstrap-specific/bootstrap-horizontal/horizontal-wrapper.ts

docs(demo): add validation messages to bs-horizontal wrapper

---

src/core/src/lib/components/formly.attributes.spec.ts
src/core/src/lib/components/formly.attributes.ts

fix(core): mark formControl as dirty on change event

---

src/core/src/lib/extensions/field-form/utils.spec.ts
src/core/src/lib/extensions/field-form/utils.ts

fix(core): avoid removing the wrong formControl instance on hide

---

src/material/select/src/select.spec.ts
src/material/select/src/select.type.ts

fix(material): use passed aria-labelledby attr for select type

---

src/core/src/lib/extensions/field-expression/field-expression.spec.ts
src/core/src/lib/extensions/field-expression/field-expression.ts

fix(core): avoid checking parent field on eval hide expression

---

demo/src/app/examples/advanced/json-schema/config.module.ts
demo/src/app/guides/validation.md

docs: remove NgModule declaration of async validators info

---

src/material/datepicker/src/datepicker.type.ts

fix(material): ensure showing datepicker icon wehn OnPush enabled

---

.travis.yml
src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/templates/field-array.type.spec.ts
src/core/src/lib/templates/field-array.type.ts

fix(core): allow nullable value for array type

---

src/core/json-schema/src/formly-json-schema.service.spec.ts
src/core/json-schema/src/formly-json-schema.service.ts

fix(json-schema): guess nullable and single array type

---

src/core/src/lib/utils.spec.ts
src/core/src/lib/utils.ts

fix(core): better clone for File and moment.js instance

---

src/bootstrap/src/lib/types/radio.ts
src/core/src/lib/components/formly.attributes.ts
src/ionic/src/lib/formly.attributes.ts
src/kendo/src/lib/types/radio.ts
src/primeng/src/lib/types/radio.ts

fix(kendo): add name attr to radio type

---

demo/src/app/examples/advanced/datatable-integration/datatable.type.ts
package-lock.json
package.json

docs(demo): update ngx-datatable to the latest version

---

src/ionic/src/lib/wrappers/form-field.ts

feat(ionic): allow customize <ion-item> lines

---

src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/components/formly.form.ts

fix(core): sync value changes for fields with same key

---

src/core/src/lib/templates/field-array.type.spec.ts
src/core/src/lib/templates/field-array.type.ts

feat(core): mark the form array dirty on Add/Remove

---

src/core/src/lib/services/formly.config.spec.ts
src/core/src/lib/services/formly.config.ts

fix(core): merge existing options when replacing a field type

---

src/core/select/src/select-options.pipe.ts

refactor(core): improve managing grouped structure of select options

---

src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/components/formly.form.ts

fix(core): ensure array notation for key emit a valid model

---

src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/extensions/field-form/field-form.ts
src/core/src/lib/templates/field-array.type.ts

fix(core): ensure the validation calls occurs only once during build

---

src/core/json-schema/src/formly-json-schema.service.ts
src/core/src/lib/utils.spec.ts
src/core/src/lib/utils.ts

fix(core): change the check File instance for SSR compatibility

---

src/material/select/src/select.spec.ts
src/material/select/src/select.type.ts

fix(material): support selectAll in multiselect with group

---

src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/components/formly.form.ts

fix(core): clone initialModel during reset model

---

src/core/src/lib/extensions/field-expression/field-expression.spec.ts
src/core/src/lib/extensions/field-expression/field-expression.ts

fix(core): toggle controls of the hidden fields before the visible ones

---

src/core/src/lib/components/formly.field.spec.ts
src/core/src/lib/components/formly.field.ts

fix(core): support resolving non static fieldComponent query

---

src/ionic/src/lib/ui-ionic.module.ts

fix(ionic): add missing export of ionFormlyAttributes

---

src/core/src/lib/extensions/field-expression/field-expression.ts
src/core/src/lib/extensions/field-form/field-form.ts
src/core/src/lib/extensions/field-validation/field-validation.ts
src/core/src/lib/services/formly.form.builder.spec.ts

fix(core): update form validity when changing built-in validations

---

src/core/src/lib/components/formly.field.config.ts
src/core/src/lib/extensions/field-expression/field-expression.spec.ts
src/core/src/lib/extensions/field-expression/field-expression.ts
src/core/src/lib/services/formly.form.builder.ts
src/core/src/lib/utils.ts

fix(core): toggle control when hide changed programmatically

---

src/core/src/lib/components/formly.attributes.ts
src/core/src/lib/components/formly.field.ts
src/core/src/lib/components/formly.form.ts
src/core/src/lib/extensions/field-expression/field-expression.ts
src/core/src/lib/extensions/field-validation/field-validation.ts
src/core/src/lib/utils.ts

chore(core): improve detect firstChange for wrapProperty

---

src/core/src/lib/components/formly.field.ts

fix(core): skip detectChanges call on first render

---

src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/components/formly.form.ts

fix(core): emit a valid model when using array notation key in group

---

src/material/form-field/src/form-field.wrapper.ts

fix(material): force static query for FormField wrapper

---

src/core/json-schema/src/formly-json-schema.service.spec.ts
src/core/json-schema/src/formly-json-schema.service.ts

fix(json-schema): handle oneOf when resolving schema deps

---

src/core/src/lib/components/formly.attributes.ts
src/core/src/lib/utils.ts

fix(core): avoid recursive focus/blur calls

---

src/core/src/lib/extensions/field-expression/field-expression.spec.ts
src/core/src/lib/extensions/field-expression/field-expression.ts

fix(core): propagate disabled state to hidden fields

---

src/material/form-field/src/form-field.wrapper.ts

fix(material): allow prefix/suffix focus

---

src/core/src/lib/components/formly.field.ts

fix(core): move field first render call to onChanges

---

src/core/src/lib/extensions/core/core.ts
src/core/src/lib/extensions/field-form/field-form.ts
src/core/src/lib/extensions/field-form/utils.spec.ts
src/core/src/lib/extensions/field-form/utils.ts
src/core/src/lib/services/formly.form.builder.spec.ts

fix #1528, fix #1722, fix #1743

fix(core): propagate disabled state to subfields

---

src/core/json-schema/src/formly-json-schema.service.spec.ts
src/core/json-schema/src/formly-json-schema.service.ts

fix(json-schema): verify templateOptions exists on field

---

src/core/json-schema/src/formly-json-schema.service.spec.ts
src/core/json-schema/src/formly-json-schema.service.ts

fix(json-schema): take account of model value on resolve oneOf schema

---

src/core/src/lib/components/formly.form.ts

fix: https://github.com/JsDaddy/ngx-mask/issues/597#issuecomment-560298282

fix(core): fix max calls error when dealing with sync valueChanges

---

src/bootstrap/src/lib/types/select.ts

fix(bootstrap): add missing compareWith input to the select type

---

src/ionic/src/lib/types/datetime.ts
src/ionic/src/lib/types/select.ts

fix(ionic): add missing dialog text inputs

---

demo/src/app/examples/validation/matching-two-fields/app.component.ts
src/core/src/lib/extensions/field-form/field-form.spec.ts
src/core/src/lib/extensions/field-form/field-form.ts
src/core/src/lib/extensions/field-validation/field-validation.spec.ts
src/core/src/lib/extensions/field-validation/field-validation.ts

feat(core): support validations for fieldGroup with empty key

---

src/core/src/lib/extensions/field-form/field-form.ts
src/core/src/lib/extensions/field-form/utils.spec.ts
src/core/src/lib/extensions/field-form/utils.ts

fix(core): avoid touching hidden field control on re-build

---

src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/extensions/field-expression/field-expression.ts
src/core/src/lib/extensions/field-form/field-form.ts
src/core/src/lib/extensions/field-form/utils.spec.ts
src/core/src/lib/extensions/field-form/utils.ts
src/core/src/lib/templates/field-array.type.ts

fix(core): reduce the amount of emitted valueChanges event

---

src/core/src/lib/components/formly.attributes.ts
src/ionic/src/lib/formly.attributes.ts

perf(core): reduce the registered formlyAttributes event listeners

---

demo/src/app/examples/advanced/json-schema/config.module.ts
demo/src/assets/json-schema/schema_dependencies_json
src/core/json-schema/src/formly-json-schema.service.spec.ts
src/core/json-schema/src/formly-json-schema.service.ts
src/core/src/lib/components/formly.form.ts
src/core/src/lib/extensions/core/core.ts
src/core/src/lib/extensions/field-expression/field-expression.ts
src/core/src/lib/extensions/field-form/utils.ts

fix(json-schema): assign default value when the field is shown

---

src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/components/formly.form.ts

fix(core): take account of custom formControl value changes

---

src/bootstrap/src/lib/types/select.ts
src/core/select/src/select-options.pipe.ts
src/material/native-select/src/native-select.type.ts

perf(bootstrap): improve render time of long list for select type

---

src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/components/formly.form.ts
src/core/src/lib/extensions/field-expression/field-expression.ts
src/core/src/lib/templates/field-array.type.spec.ts

fix(core): rely on ngZone to detect changes instead of changeDetectorRef

---

src/core/src/lib/components/formly.field.spec.ts
src/core/src/lib/components/formly.field.ts
src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/utils.spec.ts
src/core/src/lib/utils.ts

fix(core): improve detect changes of formly-field host binding

---

src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/components/formly.form.ts

fix(core): detect expression changes on submit

---

src/bootstrap/src/lib/types/select.ts

fix(bootstrap): rely on accessor to select empty option

---

src/core/src/lib/extensions/field-expression/field-expression.ts

fix(core): detect observable expression changes when using OnPush CD

---

demo/src/index.html
demo/src/polyfills.ts
package-lock.json
package.json
src/bootstrap/src/lib/types/multicheckbox.ts
src/core/json-schema/src/formly-json-schema.service.ts
src/core/src/lib/extensions/field-form/utils.ts
src/material/multicheckbox/src/multicheckbox.type.ts

fix(core): avoid using includes for IE compatibility

---

src/core/src/lib/utils.spec.ts
src/core/src/lib/utils.ts

fix(core): ensure wrapProperty fn is removed after unsubscribe

---

src/core/src/lib/components/formly.field.spec.ts
src/core/src/lib/components/formly.field.ts
src/core/src/lib/components/formly.form.spec.ts

fix #2060, fix #2065, fix #2045

fix(core): create field type instance for each formly-field component

---

src/core/src/lib/components/formly.attributes.spec.ts
src/core/src/lib/components/formly.attributes.ts

fix(core): use id @input when is set instead of field id

---

src/core/src/lib/templates/field-array.type.spec.ts
src/core/src/lib/templates/field-array.type.ts

feat(core): all Add/Remove field array without triggering form as dirty

---

src/core/src/lib/templates/field-template.type.ts

feat(core): add safeHtml opt to bypass sanitizing template HTML content

---

demo/src/app/examples/bootstrap-formly/select/app.component.ts
src/core/select/src/select-options.pipe.spec.ts
src/core/select/src/select-options.pipe.ts

feat(core): allow pass already grouped structure to select options

---

src/core/src/lib/extensions/field-expression/field-expression.spec.ts
src/core/src/lib/extensions/field-expression/field-expression.ts

fix(core): take account of passing observable to model expr

---

src/core/src/lib/components/formly.field.ts
src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/components/formly.form.ts

fix(core): ensure UI is in sync when using custom checkExpressionOn

---

src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/components/formly.form.ts

fix(core): take account of the emitted modelChange value as model input

---

src/core/src/lib/extensions/field-expression/field-expression.ts
src/core/src/lib/extensions/field-form/field-form.ts
src/core/src/lib/extensions/field-form/utils.ts
src/core/src/lib/extensions/field-validation/field-validation.ts

fix(core): emit statusChanges on updateValueAndValidity

---

src/material/checkbox/src/checkbox.type.ts
src/material/multicheckbox/src/multicheckbox.type.ts

fix(material): handle undefined color palette for checkbox

---

demo/src/app/guides/introduction.md
src/core/src/lib/extensions/core/core.ts

fix(core): allow passing a custom type when template is null

---

src/core/src/lib/extensions/field-expression/field-expression.spec.ts
src/core/src/lib/extensions/field-expression/field-expression.ts

fix(core): disabled expression should not overwrites child expression

---

src/material/datepicker/src/datepicker.type.ts

feat(material): add dateInput and dateChange options to datepicker type

---

src/bootstrap/src/lib/types/checkbox.ts
src/bootstrap/src/lib/types/multicheckbox.ts
src/bootstrap/src/lib/types/radio.ts

feat(bootstrap): support custom-inline for radio/checkbox

---

README.md

Updated the README.md.
I have created a post on Medium for people on how to create JSON-Powered Forms in Angular with ngx-formly.
I don't know if you want this, but I'm thankful for the tool you build so everyone can use it! 🙏. So if you don't want to add it, it's no problem for me 😉

doc: added blogpost link in the readme

---

src/primeng/src/lib/wrappers/form-field.ts

https://primefaces.org/primeng/showcase/#/validation
Changed class names according to documentation PrimeNG
fix #2135

fix(primeng): change class ui-messages-error to ui-message-error

---

src/core/src/lib/services/formly.config.spec.ts
src/core/src/lib/services/formly.config.ts

fix(core): ensure showError option return a boolean value

---

src/schematics/src/collection.json

Fixes #2177
None for the lib itself, crash for tools using it.
None for the lib itself, not crashing for tools using it.

fix(schematics): remove comments in collection.json

---

src/core/json-schema/src/formly-json-schema.service.spec.ts
src/core/json-schema/src/formly-json-schema.service.ts
src/core/src/lib/components/formly.field.spec.ts

fix(json-schema): take acocunt of total matched oneOf props

---

src/core/src/lib/components/formly.field.spec.ts
src/core/src/lib/components/formly.field.ts

fix(core): ensure field is not empty when calling hooks

---

src/core/src/lib/components/formly.field.config.ts
src/core/src/lib/extensions/field-expression/field-expression.spec.ts
src/core/src/lib/extensions/field-expression/field-expression.ts
src/core/src/lib/services/formly.form.builder.spec.ts

fix(core): support Content-Security-Policy header script-src 'self'

---

demo/src/app/examples/advanced/datatable-integration/app.component.ts
demo/src/app/examples/advanced/grid-integration/app.component.ts
demo/src/app/examples/advanced/repeating-section/app.component.ts
demo/src/app/examples/bootstrap-specific/input-add-ons/config.module.ts
demo/src/app/examples/other/material-prefix-suffix/addons.wrapper.ts
demo/src/app/examples/other/material-prefix-suffix/app.component.ts
demo/src/app/examples/other/material-prefix-suffix/app.module.ts
demo/src/app/shared/example-viewer/example-viewer.component.html
demo/src/app/shared/example-viewer/example-viewer.component.ts
demo/src/app/shared/stackblitz/stackblitz-writer.ts

docs(demo): add fontawesome style in stackblitz addon example

---

src/material/multicheckbox/src/multicheckbox.type.ts

fix(material): take account of disabled state for multicheckbox type

---

demo/src/app/examples/advanced/i18n-alternative/app.component.ts
demo/src/app/examples/advanced/i18n-alternative/translate.extension.ts
demo/src/app/examples/advanced/i18n/app.component.ts
demo/src/app/examples/advanced/i18n/app.module.ts
demo/src/assets/i18n/en_json
demo/src/assets/i18n/fr_json
src/core/src/lib/services/formly.config.ts
src/core/src/lib/templates/formly.validation-message.spec.ts
src/core/src/lib/templates/formly.validation-message.ts

feat(core): support passing observable for validation message

---

demo/src/app/examples/advanced/repeating-section-input/app.component.ts
src/core/src/lib/components/formly.field.spec.ts
src/core/src/lib/components/formly.field.ts
src/core/src/lib/extensions/field-expression/field-expression.ts

feat(core): allow onInit/afterView/afterContent to return observables

---

demo/src/app/examples/advanced/i18n-alternative/app.component.ts
demo/src/app/examples/advanced/i18n/app.component.ts
src/core/src/lib/components/formly.field.config.ts
src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/components/formly.form.ts

feat(core): add valueChange prop for UI & programmatically changes

---

src/core/src/lib/core.ts
src/material/radio/src/radio.type.ts

fix(material): take account of radio button focus on page load

---

demo/src/app/examples/validation/custom-validation/app.module.ts
src/bootstrap/src/lib/types/checkbox.ts
src/bootstrap/src/lib/types/multicheckbox.ts

feat(bootstrap): support switch style checkboxes

---

src/core/src/lib/components/formly.form.ts
src/core/src/lib/extensions/core/core.ts
src/core/src/lib/extensions/field-form/utils.ts
src/core/src/lib/templates/field-array.type.spec.ts
src/core/src/lib/templates/field-array.type.ts
src/core/src/lib/utils.spec.ts
src/core/src/lib/utils.ts

feat(core): allow nullable value for group type

---

demo/src/app/app.component.ts
demo/src/app/examples/examples.module.ts
demo/src/app/examples/validation/custom-validation-parameters/app.component.html
demo/src/app/examples/validation/custom-validation-parameters/app.component.ts
demo/src/app/examples/validation/custom-validation-parameters/app.module.ts
demo/src/app/examples/validation/custom-validation-parameters/config.module.ts
src/core/src/lib/extensions/field-validation/field-validation.ts
src/core/src/lib/services/formly.config.ts
src/core/src/lib/services/formly.form.builder.spec.ts

feat(core): add an alternative way for passing parameters to validation

---

src/material/datepicker/src/datepicker.type.ts

feat(material): add missing mat-datepicker inputs to datepickerOptions

---

src/bootstrap/src/lib/types/select.ts
src/ionic/src/lib/types/select.ts
src/material/select/src/select.type.ts

feat(ionic): add compareWith input for select type

---

src/schematics/src/ng-add/index_spec.ts
src/schematics/src/wrapper-component/index_spec.ts
src/schematics/utils/ast.ts

fix(schematics): rely sourceRoot to get the project path

---

src/core/src/lib/components/formly.form.ts

fix(core): keep the model in-sync with the root field

---

src/material/input/src/input.type.ts

fix(material): use false for input static query

---

src/core/src/lib/services/formly.config.spec.ts
src/core/src/lib/services/formly.config.ts

fix(core): provide more details on missing type declaration

---

src/core/json-schema/src/formly-json-schema.service.spec.ts
src/core/select/src/select-options.pipe.spec.ts
src/core/src/lib/components/formly.field.ts
src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/components/formly.form.ts
src/core/src/lib/extensions/core/core.spec.ts
src/core/src/lib/extensions/core/core.ts
src/core/src/lib/extensions/field-expression/field-expression.spec.ts
src/core/src/lib/extensions/field-expression/field-expression.ts
src/core/src/lib/extensions/field-form/field-form.spec.ts
src/core/src/lib/extensions/field-validation/field-validation.spec.ts
src/core/src/lib/extensions/field-validation/field-validation.ts
src/core/src/lib/models/fieldconfig.cache.ts
src/core/src/lib/models/fieldconfig.ts
src/core/src/lib/services/formly.builder.spec.ts
src/core/src/lib/services/formly.builder.ts
src/core/src/lib/templates/field-array.type.spec.ts
src/core/src/lib/templates/field-array.type.ts
src/core/testing/src/component-factory.ts
src/ui/material/form-field/src/form-field.wrapper.ts

feat(core): expose build, detectChanges and checkExpressions in options

---

README.md
src/core/src/lib/components/formly.field.spec.ts
src/core/src/lib/components/formly.field.ts
src/core/src/lib/extensions/core/core.ts
src/core/src/lib/services/formly.builder.ts
src/core/src/lib/templates/field-array.type.spec.ts
src/core/src/lib/templates/field-template.type.spec.ts
src/core/src/lib/utils.spec.ts
src/core/src/lib/utils.ts
src/core/testing/src/component-factory.ts

fix(core): detect changes of formState and on rebuild

---

src/core/src/lib/components/formly.attributes.ts

fix(core): ensure change event is called after the formControl change

---

src/schematics/src/ng-add/index.ts
src/schematics/src/ng-add/index_spec.ts
src/schematics/src/ng-add/schema.ts

fix(schematics): add ng-zorro-antd to ui-theme option

---

src/ionic/src/lib/types/datetime.ts

fix(ionic): add missing Names && ShortNames inputs for datetime picker

---

src/bootstrap/src/lib/types/checkbox.ts

feat(bootstrap): support checkbox without label

---

src/material/datepicker/src/datepicker.type.ts

feat(material): add monthSelected && yearSelected outputs for datepicker

---

src/core/src/lib/extensions/field-validation/field-validation.ts

feat(core): support attach error to specific field from a validator

---

package.json

ci: remove postinstall scripts

---

.gitpod.Dockerfile
.gitpod.yml
README.md

This commit implements a fully-automated development setup using Gitpod.io, an
online IDE for GitHub and GitLab that enables Dev-Environments-As-Code.
This makes it easy for anyone to get a ready-to-code workspace for any branch,
issue or pull request almost instantly with a single click.

chore: add gitpod config

---

src/material/checkbox/src/checkbox.type.ts
src/material/radio/src/radio.type.ts

fix(material): rely on checkbox change input instead of formly attr

---

src/core/src/lib/components/formly.field.config.ts
src/core/src/lib/extensions/field-expression/field-expression.spec.ts
src/core/src/lib/extensions/field-expression/field-expression.ts

feat(core): emit expressionChanges event through fieldChanges option

---

src/material/checkbox/src/checkbox.type.ts

fix(material): revert required behavior for checkbox

---

src/core/src/lib/components/formly.field.config.ts
src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/extensions/field-form/utils.ts
src/core/src/lib/utils.ts

feat(core): allow passing number or array to field key

---

src/core/src/lib/extensions/field-form/field-form.ts
src/core/src/lib/templates/field-array.type.spec.ts
src/core/src/lib/utils.ts

fix(core): avoid unnecessary valueChanges on add/remove field array

---

src/material/slider/src/slider.type.ts
src/material/toggle/src/toggle.type.ts

fix(material): add change event for toggle and slider types

---

src/core/src/lib/extensions/field-form/utils.spec.ts
src/core/src/lib/extensions/field-form/utils.ts

fix(core): avoid re-parse nested field key

---

demo/src/app/shared/stackblitz/stackblitz-writer.ts

docs(demo): update kendo stackblitz deps

---

src/core/json-schema/src/formly-json-schema.service.spec.ts
src/core/json-schema/src/formly-json-schema.service.ts
src/core/src/lib/components/formly.field.config.ts
src/core/src/lib/extensions/field-expression/field-expression.ts
src/core/src/lib/services/formly.form.builder.ts

fix(json-schema): manage oneOf of duplicated field property

---

src/core/src/lib/extensions/field-validation/field-validation.ts

fix(core): take account of async validators errorPath

---

src/core/src/lib/components/formly.attributes.spec.ts
src/core/src/lib/components/formly.attributes.ts

fix(core): pass a valid event instance for change fn

---

src/core/src/lib/extensions/field-validation/field-validation.ts

feat(core): support multiple errors from a single validator

---

src/core/json-schema/src/formly-json-schema.service.ts

fix(json-schema): support oneOf with $ref definition

---

src/core/src/lib/components/formly.attributes.ts
src/material/checkbox/src/checkbox.type.ts
src/material/radio/src/radio.type.ts
src/material/slider/src/slider.type.ts
src/material/toggle/src/toggle.type.ts

fix(core): revert change event to host

---

src/core/json-schema/src/formly-json-schema.service.ts
src/core/src/lib/extensions/field-form/field-form.spec.ts
src/core/src/lib/extensions/field-form/field-form.ts
src/core/src/lib/extensions/field-form/utils.ts

feat(core): support form control for field with empty key

---

src/schematics/package.json

fix(schematics): update angular-devkit deps

---

src/core/src/lib/components/formly.field.ts
src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/services/formly.config.ts
src/schematics/src/ng-add/index.ts
src/schematics/src/ng-add/index_spec.ts

feat(core): lazily render component field type

---

src/core/src/lib/templates/field-array.type.spec.ts
src/core/src/lib/templates/field-array.type.ts

fix(core): share formControl for array field when key is duplicated

---

src/core/json-schema/src/formly-json-schema.service.spec.ts
src/core/json-schema/src/formly-json-schema.service.ts
src/core/src/lib/extensions/field-form/utils.ts

 feat(json-schema): allow passing mixed type in oneOf 

---

src/core/json-schema/src/formly-json-schema.service.spec.ts
src/core/json-schema/src/formly-json-schema.service.ts
src/core/src/lib/extensions/field-expression/field-expression.ts
src/core/src/lib/extensions/field-form/utils.ts

fix(json-schema): avoid reset on hide during the build step

---

src/core/json-schema/src/formly-json-schema.service.spec.ts
src/core/json-schema/src/formly-json-schema.service.ts
src/core/src/lib/core.ts
src/core/src/lib/utils.ts

fix(json-schema): support nested oneOf

---

src/core/json-schema/src/formly-json-schema.service.spec.ts
src/core/json-schema/src/formly-json-schema.service.ts

fix(json-schema): avoid rely on default value for select oneOf item

---

src/core/json-schema/src/formly-json-schema.service.spec.ts
src/core/json-schema/src/formly-json-schema.service.ts

 fix(json-schema): take account of passing float to multipleOf validation

---

src/material/form-field/src/form-field.wrapper.ts

fix(material): apply a11y for validation messages

---

src/core/src/lib/services/formly.config.ts

fix(core): avoid memory leakes for internal componentRefs

---

demo/src/app/examples/advanced/json-schema/app.module.ts
src/core/json-schema/src/formly-json-schema.service.spec.ts
src/core/json-schema/src/formly-json-schema.service.ts
src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/extensions/core/core.ts
src/core/src/lib/extensions/field-expression/field-expression.ts
src/core/src/lib/services/formly.config.ts
src/core/src/lib/utils.ts

fix #1847, fix #2381, fix #2439

 feat(core): add option to resetFieldOnHide

---

src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/extensions/core/core.ts
src/core/src/lib/extensions/field-expression/field-expression.ts

fix(core): apply defaultValue for array when resetFieldOnHide enabled

---

src/core/src/lib/extensions/field-expression/field-expression.ts

fix(core): move eval expression to post populate

---

src/material/checkbox/src/checkbox.type.ts
src/material/input/src/input.type.ts
src/material/multicheckbox/src/multicheckbox.type.ts
src/material/select/src/select.type.ts
src/material/slider/src/slider.type.ts
src/material/toggle/src/toggle.type.ts

fix(material): rely on tabIndex input instead of attr

---

src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/utils.ts

fix(core): remove parent check on assign nullable value

---

src/material/radio/src/radio.type.ts

fix(material): delay radio focus on status changes

---

src/core/src/lib/extensions/field-expression/field-expression.ts

fix(core): improve expression error message

---

src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/extensions/field-expression/field-expression.ts
src/core/src/lib/utils.ts

fix(core): clear value on hide for array type

---

src/core/src/lib/extensions/field-expression/field-expression.spec.ts
src/core/src/lib/extensions/field-expression/field-expression.ts

fix(core): supports array notation in expression property

---

src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/components/formly.form.ts
src/core/src/lib/extensions/field-form/utils.ts

fix(core): clear validation cache on fields input change

---

src/core/src/lib/templates/field-array.type.ts

fix(core): avoid overriding accessor by property

---

src/core/src/lib/extensions/field-form/utils.ts

fix(core): avoid creation a dummy field for nested key

---

src/ionic/package.json

fix(ionic): add v5 to peer dependencies

---

src/material/select/src/select.type.ts

fix(material): ignore disabled option on selectAll

---

src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/extensions/field-expression/field-expression.spec.ts
src/core/src/lib/extensions/field-expression/field-expression.ts

fix(core): apply default value on hide changes for nested object

---

src/core/src/lib/extensions/field-form/utils.spec.ts
src/core/src/lib/extensions/field-form/utils.ts

fix(core): take account of parent disable state on init

---

src/material/checkbox/src/checkbox.type.ts

fix(material): trigger focus/blur event for mat-checkbox

---

src/core/src/lib/extensions/field-form/utils.ts

fix(core): detect disabled state for CD OnPush components

---

src/material/datepicker/src/datepicker.type.ts

fix(material): assign disable state to datepicker-toggle

---

src/material/checkbox/src/checkbox.type.ts

fix(material): handle checkbox destroy

---

src/core/json-schema/src/formly-json-schema.service.ts
src/core/src/lib/components/formly.field.config.ts
src/core/src/lib/extensions/core/core.ts
src/core/src/lib/extensions/field-expression/field-expression.ts
src/core/src/lib/utils.ts

fix(core): allow control resetOnHide for a specific field

---

src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/components/formly.form.ts

fix(core): take account of default value on resetModel

---

demo/src/app/examples/advanced/multi-step-form/app.module.ts

docs(demo): make stepper compatible with material-ui

---

src/ionic/src/lib/types/select.ts

fix(ionic): apply full width for select floating position

---

demo/src/app/app.component.ts
demo/src/app/examples/examples.module.ts
demo/src/app/examples/other/material-formfield-hint-align/app.component.html
demo/src/app/examples/other/material-formfield-hint-align/app.component.ts
demo/src/app/examples/other/material-formfield-hint-align/app.module.ts
demo/src/app/examples/other/material-formfield-hint-align/config.module.ts
package-lock.json
src/ui/material/form-field/src/field.type.ts
src/ui/material/form-field/src/form-field.wrapper.ts
src/ui/material/select/src/select.type.spec.ts

feat(material): mat-hint alignment support

---

src/core/src/lib/core.module.ts

fix(core): always run first core extensions

---

src/core/json-schema/src/formly-json-schema.service.spec.ts
src/core/json-schema/src/formly-json-schema.service.ts

fix(json-schema): use disabled for readOnly option

---

src/core/src/lib/services/formly.config.spec.ts
src/core/src/lib/services/formly.config.ts

fix(core): skip merge wrappers when explicitly set

---

src/core/json-schema/src/formly-json-schema.service.ts

fix(json-schema): avoid calling map twice

---

src/core/json-schema/src/formly-json-schema.service.spec.ts
src/core/json-schema/src/formly-json-schema.service.ts

 fix(json-schema): support readOnly for oneOf/AnyOf schema

---

src/ionic/src/lib/types/datetime.ts

fix(ionic): add alternative way to specify min/max date

---

src/core/src/lib/extensions/field-expression/field-expression.ts

fix(core): emit statusChange on field hide

---

src/core/src/lib/components/formly.form.ts

fix(core): detect mutable value changes

---

src/core/src/lib/core.module.ts
src/core/src/lib/templates/field-array.type.ts

fix(core): make FieldArray compatible with Angular 11

---

src/schematics/utils/ast.ts

 fix(schematics): add support for Angular 11.1

---

src/core/src/lib/components/formly.form.ts

fix(core): ignore whitespaces for content projection check

---

CHANGELOG.md
src/schematics/package.json

fix(schematics): move to dev dependencies

---

src/core/src/lib/components/formly.field.ts
src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/components/formly.form.ts
src/core/src/lib/components/formly.template.ts
src/core/src/lib/core.module.ts
src/core/src/lib/extensions/core/core.ts
src/core/src/lib/models/fieldconfig.cache.ts
src/core/src/lib/services/formly.config.spec.ts
src/core/src/lib/services/formly.config.ts

feat(core): add support for inline type

---

demo/src/app/examples/advanced/json-schema/app.module.ts
src/core/json-schema/src/formly-json-schema.service.spec.ts
src/core/src/lib/components/formly.field.spec.ts
src/core/src/lib/components/formly.field.ts
src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/models/config.ts
src/core/src/lib/services/formly.config.ts

feat(core): allow omit formly-field element

---

package.json

fix: clean dist folder on build

---

src/schematics/src/ng-add/schema.json

fix(schematics): allow passing --project option to ng-add

---

src/core/src/lib/extensions/field-form/utils.ts

fix(core): preserve validation cache for detached fields

---

src/material/datepicker/src/datepicker.type.ts
src/material/form-field/src/form-field.wrapper.ts

fix(material): allow re-use internal prefix & suffix

---

src/core/json-schema/src/formly-json-schema.service.spec.ts
src/core/json-schema/src/formly-json-schema.service.ts

fix(json-schema): select all populated anyOf schemas

---

src/material/select/src/select.type.ts

fix(material): mark as dirty on selectAll options

---

src/core/json-schema/src/formly-json-schema.service.spec.ts
src/core/json-schema/src/formly-json-schema.service.ts

fix(json-schema): take account of optional object with required props

---

src/core/src/lib/extensions/field-form/field-form.ts

 fix(core): ensure validators key is defined on build

---

src/core/json-schema/src/formly-json-schema.service.ts

fix(json-schema): resolve recursive schema when using widget

---

src/material/select/src/select.type.ts

fix(material): allow passing aria-label to mat-select

---

src/material/checkbox/src/checkbox.type.ts
src/material/datepicker/src/datepicker.type.ts
src/material/radio/src/radio.type.ts

fix(material): use ViewChild static query for checkbox

---

src/core/json-schema/src/formly-json-schema.service.spec.ts
src/core/json-schema/src/formly-json-schema.service.ts

fix(json-schema): take account of multischema required prop

---

src/core/src/lib/utils.spec.ts
src/core/src/lib/utils.ts

fix(core): support Set/Map in immutable mode

---

src/core/src/lib/components/formly.field.ts

fix(core): prevent unnecessary wrapper re-render

---

src/core/src/lib/extensions/field-form/field-form.ts

fix(core): detect form validation changes on build

---

src/core/src/lib/extensions/field-form/field-form.ts
src/core/src/lib/services/formly.form.builder.spec.ts

fix(core): take account of previously disabled control

---

src/core/json-schema/src/formly-json-schema.service.ts

fix(json-schema): detect change of multischema

---

src/core/json-schema/src/formly-json-schema.service.spec.ts
src/core/json-schema/src/formly-json-schema.service.ts

fix(json-schema): improve validation of multipleOf with decimal numbers

---

src/core/json-schema/src/formly-json-schema.service.spec.ts
src/core/json-schema/src/formly-json-schema.service.ts

fix(json-schema): support passing widget with $ref definition

---

package-lock.json
src/ui/material/datepicker/src/datepicker.type.ts

feat(material): add calendarHeaderComponent input for datepicker

---

src/ui/material/select/src/select.type.ts

feat(material): add typeaheadDebounceInterval input for select

---

src/ui/material/slider/src/slider.type.ts

feat(material): add slider missing inputs

---

demo/src/app/guides/custom-formly-wrapper.md

docs: fix typo

---

src/material/form-field/src/form-field.wrapper.scss
src/material/form-field/src/form-field.wrapper.ts

fix(material): support passing long error message

---

src/bootstrap/src/lib/types/checkbox.ts
src/bootstrap/src/lib/wrappers/form-field.wrapper.ts
src/ionic/src/lib/wrappers/form-field.ts
src/kendo/src/lib/types/checkbox.ts
src/kendo/src/lib/wrappers/form-field.ts
src/material/checkbox/src/checkbox.type.ts
src/material/form-field/src/form-field.wrapper.ts
src/primeng/src/lib/wrappers/form-field.ts

fix(core): set aria-hidden to required marker

---

src/core/json-schema/src/formly-json-schema.service.spec.ts
src/core/json-schema/src/formly-json-schema.service.ts

fix(json-schema): handle array type without items keyword

---

src/core/json-schema/src/formly-json-schema.service.ts

Bug fix
https://github.com/ngx-formly/ngx-formly/issues/2898
N/A

fix(json-schema): take account of empty model in required expr

---

src/core/src/lib/components/formly.attributes.spec.ts
src/core/src/lib/components/formly.attributes.ts

fix(core): allow overriding the default build-in html attributes

---

src/core/src/lib/extensions/field-expression/field-expression.ts
src/core/src/lib/services/formly.form.builder.spec.ts

fix(core): improve stream source comparison of expressionProperties

---

src/core/src/lib/extensions/field-expression/field-expression.spec.ts
src/core/src/lib/extensions/field-expression/field-expression.ts

fix(core): improve parse array notation in expression property

---

README.md
angular.json
demo/src/app/examples/validation/custom-validation-parameters/config.module.ts
demo/src/app/examples/validation/matching-two-fields/config.module.ts
demo/src/app/guides/custom-formly-field.md
demo/src/app/guides/custom-formly-wrapper.md
demo/src/app/guides/expression-properties.md
demo/src/app/guides/introduction.md
demo/src/app/guides/properties-options.md
demo/src/app/guides/validation.md

Docs update: I fixed many small typos and added some words or rephrased things. Let me know if you don't like anything :)

docs: various typos and small improvements

---

UPGRADE-6.0.md
demo/src/app/examples/bootstrap-specific/advanced-layout/config.module.ts
demo/src/app/examples/bootstrap-specific/bootstrap-horizontal/horizontal-wrapper.ts
demo/src/app/examples/form-options/form-state/app.component.html
demo/src/styles.scss
package-lock.json
package.json
src/ui/bootstrap/addons/src/addons.component.html
src/ui/bootstrap/checkbox/src/checkbox.type.spec.ts
src/ui/bootstrap/checkbox/src/checkbox.type.ts
src/ui/bootstrap/form-field/src/form-field.wrapper.spec.ts
src/ui/bootstrap/form-field/src/form-field.wrapper.ts
src/ui/bootstrap/multicheckbox/src/multicheckbox.type.ts
src/ui/bootstrap/package.json
src/ui/bootstrap/radio/src/radio.type.spec.ts
src/ui/bootstrap/radio/src/radio.type.ts
src/ui/bootstrap/select/src/select.type.ts

Update bootstrap to v5
Bootstrap v4 is used
Bootstrap v5 is used
N/A (visual changes should be none if possible)
I had a go at implementing floating labels, however this would require the form control to be a direct sibling to the label, which I'm not sure is possible currently. Alternatively we could include the entire floating label css but rewritten (the first option would be ideal however). …

Bootstrap 5 support

---

UPGRADE-6.0.md
src/core/src/lib/components/formly.field.ts
src/core/src/lib/utils.spec.ts
src/core/src/lib/utils.ts

fix(core): improve detection changes of templateOptions props

---

src/core/src/lib/components/formly.field.spec.ts
src/core/src/lib/components/formly.field.ts
src/core/src/lib/components/formly.form.ts
src/core/src/lib/extensions/field-expression/field-expression.ts
src/core/src/lib/extensions/field-form/field-form.ts

fix(core): improve handling fields changes while building

---

src/core/src/lib/extensions/field-expression/field-expression.spec.ts
src/core/src/lib/extensions/field-expression/field-expression.ts

fix(core): re-check expression when detecting new field changes

---

src/kendo/src/lib/types/textarea.ts
src/primeng/src/lib/types/textarea.ts

fix(kendo): support rows and cols in text-area

---

demo/src/app/examples/advanced/json-schema/array.type.ts
src/core/json-schema/src/formly-json-schema.service.spec.ts
src/core/json-schema/src/formly-json-schema.service.ts

fix(json-schema): add removable prop to array tuples

---

src/core/src/lib/components/formly.field.ts
src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/extensions/field-expression/field-expression.spec.ts

fix(core): remove className when lazyRender is enable

---

src/core/src/lib/utils.ts

fix(core): handle TemplateRef clone

---

.github/workflows/ci.yml
package-lock.json
src/core/src/lib/utils.spec.ts
src/core/src/lib/utils.ts

fix(core): clear cached value of observed object

---

demo/src/app/examples/other/material-prefix-suffix/addons.wrapper.ts
src/ui/material/form-field/src/field.type.ts

fix(material): assign prefix to templateOptions instead of field

---

src/core/json-schema/src/formly-json-schema.service.spec.ts
src/core/json-schema/src/formly-json-schema.service.ts
src/core/src/lib/extensions/field-expression/field-expression.ts

fix(json-schema): take account of oneOf model change

---

src/core/json-schema/src/formly-json-schema.service.ts

fix(json-schema): take account of undefined value for integer type 

---

src/core/src/lib/extensions/field-form/utils.spec.ts
src/core/src/lib/extensions/field-form/utils.ts

fix(core): emit valueChanges when FormControl value changes

---

src/core/src/lib/extensions/field-expression/field-expression.spec.ts
src/core/src/lib/extensions/field-expression/field-expression.ts

fix(core): improve detecting changes when using Function in expression

---

src/core/src/lib/extensions/field-expression/field-expression.ts
src/core/src/lib/extensions/field-form/utils.ts

fix(core): clear cache of registered fields on hide.

---

src/material/form-field/src/form-field.wrapper.scss

fix(material): remove mat-form-field static position

---

README.md
demo/src/app/examples/advanced/datatable-integration/app.module.ts
demo/src/app/examples/advanced/grid-integration/app.module.ts
demo/src/app/examples/advanced/i18n-alternative/app.module.ts
demo/src/app/shared/stackblitz/stackblitz-button.ts
demo/src/app/shared/stackblitz/stackblitz-writer.ts
demo/src/app/shared/stackblitz/stackblitz.config.ts
demo/src/assets/stackblitz/.stackblitzrc
demo/src/assets/stackblitz/angular_json
demo/src/assets/stackblitz/environment.prod.ts
demo/src/assets/stackblitz/environment.ts
demo/src/assets/stackblitz/index.html
demo/src/assets/stackblitz/tsconfig.app_json
demo/src/assets/stackblitz/tsconfig_json
package-lock.json
package.json

docs(demo): use stackblitz sdk

---

src/material/slider/src/public_api.ts
src/material/slider/src/slider.module.ts
src/material/slider/src/slider.type.ts

fix(core): clear cache of registered fields on hide. (

---

src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/extensions/field-form/utils.ts

fix(core): update validation of root form on fields change

---

src/material/datepicker/src/datepicker.module.ts
src/material/datepicker/src/datepicker.type.ts
src/material/datepicker/src/public_api.ts
src/material/toggle/src/public_api.ts
src/material/toggle/src/toggle.module.ts
src/material/toggle/src/toggle.type.ts

- packaging
- naming
- fix #3094 comments
- fix #3116 
- exports addressed
- new names comply with convention

fix(material): export datepicker and toggle types

---

src/core/src/lib/components/formly.field.spec.ts
src/core/src/lib/components/formly.field.ts
src/core/src/lib/extensions/core/core.ts
src/core/src/lib/utils.ts
src/core/testing/src/input.module.ts

fix(core): detect formControl status changes

---

demo/src/app/examples/advanced/multi-step-form/stepper.type.ts
demo/src/app/examples/advanced/tabs/tabs.type.ts

demo: update stepper validation check

---

src/core/src/lib/extensions/field-expression/field-expression.ts
src/core/src/lib/extensions/field-form/field-form.ts
src/core/src/lib/extensions/field-form/utils.ts
src/core/src/lib/services/formly.form.builder.ts
src/core/src/lib/templates/field-array.type.spec.ts
src/core/src/lib/utils.ts

fix(core): optimize emitted valueChanges for fieldArray items

---

demo/src/app/app.component.html
demo/src/app/shared/example-viewer/example-viewer.component.html
demo/src/app/shared/stackblitz/stackblitz-button.html
src/material/multicheckbox/src/multicheckbox.type.ts

fix(material): fix invalid ARIA attributes in MultiCheckbox type

---

src/core/src/lib/components/formly.field.spec.ts
src/core/src/lib/extensions/core/core.ts
src/core/src/lib/models/fieldconfig.cache.ts

fix(core): update field component instance used in onPopulate

---

UPGRADE-6.0.md
demo/src/app/examples/advanced/json-schema/app.module.ts
demo/src/app/examples/advanced/json-schema/array.type.ts
src/core/json-schema/src/formly-json-schema.service.spec.ts
src/core/json-schema/src/formly-json-schema.service.ts
src/core/src/lib/components/formly.field.spec.ts
src/core/src/lib/components/formly.field.ts

feat(json-schema): add schema type validation

---

src/core/json-schema/src/formly-json-schema.service.spec.ts
src/core/json-schema/src/formly-json-schema.service.ts

feat(json-schema): support oneOf for non-object type

---

src/ui/bootstrap/addons/src/addons.component.html
src/ui/bootstrap/addons/src/addons.component.scss

feat(bootstrap): remove usage of inline-styles in addons

---

src/core/src/lib/components/formly.attributes.spec.ts
src/core/src/lib/components/formly.attributes.ts

fix(core): ignore handle attr by formlyAttributes if already set

---

src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/extensions/field-form/field-form.ts

fix(core): keep disabled state of field group consistent

---

UPGRADE-6.0.md
demo/src/app/examples/advanced/json-schema/app.module.ts
demo/src/app/examples/validation/built-in-validations/app.module.ts
demo/src/app/examples/validation/matching-two-fields/app.module.ts
demo/src/app/examples/validation/validation-message/app.module.ts
src/core/src/lib/extensions/field-validation/field-validation.spec.ts
src/core/src/lib/extensions/field-validation/field-validation.ts
src/core/src/lib/models/fieldconfig.ts
src/core/src/lib/services/formly.config.spec.ts
src/core/src/lib/services/formly.config.ts
src/core/src/lib/templates/formly.validation-message.spec.ts

feat(core): use minLength, maxLength for message validations

---

src/bootstrap/src/lib/types/multicheckbox.ts
src/material/multicheckbox/src/multicheckbox.type.ts

fix(bootstrap): support disable a specific multicheckbox option

---

src/core/json-schema/src/formly-json-schema.service.ts
src/core/src/lib/components/formly.field.ts
src/core/src/lib/components/formly.form.ts
src/core/src/lib/core.ts
src/core/src/lib/extensions/core/core.ts
src/core/src/lib/extensions/field-expression/field-expression.ts
src/core/src/lib/extensions/field-form/field-form.spec.ts
src/core/src/lib/extensions/field-form/field-form.ts
src/core/src/lib/extensions/field-form/utils.ts
src/core/src/lib/extensions/field-validation/field-validation.ts
src/core/src/lib/templates/field-array.type.ts
src/core/src/lib/utils.spec.ts
src/core/src/lib/utils.ts

fix(core): ignore passing empty string to field key

---

demo/src/app/guides/introduction.md

docs(guides): add note for Angular 13 schematics install

---

src/material/datepicker/src/datepicker.type.ts

fix(material): prioritize matDatepickerParse error over required

---

src/core/src/lib/components/formly.attributes.ts

fix(core): use host listener to catch custom change events

---

demo/src/app/ui/ui-primeng/datepicker/app.module.ts
src/core/src/lib/models/fieldconfig.ts

fix(core): update field validation messages signature

---

package-lock.json
package.json
src/ui/kendo/checkbox/src/checkbox.module.ts
src/ui/kendo/checkbox/src/checkbox.type.scss
src/ui/kendo/checkbox/src/checkbox.type.spec.ts
src/ui/kendo/checkbox/src/checkbox.type.ts
src/ui/kendo/form-field/src/field.type.ts
src/ui/kendo/form-field/src/form-field.module.ts
src/ui/kendo/form-field/src/form-field.wrapper.spec.ts
src/ui/kendo/form-field/src/form-field.wrapper.ts
src/ui/kendo/form-field/src/public_api.ts
src/ui/kendo/input/src/input.module.ts
src/ui/kendo/input/src/input.type.spec.ts
src/ui/kendo/input/src/input.type.ts
src/ui/kendo/package.json
src/ui/kendo/radio/src/radio.module.ts
src/ui/kendo/radio/src/radio.type.scss
src/ui/kendo/radio/src/radio.type.ts
src/ui/kendo/select/src/select.type.spec.ts
src/ui/kendo/select/src/select.type.ts
src/ui/kendo/textarea/src/textarea.module.ts
src/ui/kendo/textarea/src/textarea.type.spec.ts
src/ui/kendo/textarea/src/textarea.type.ts

feat(kendo): use the new formfield layout

---

src/core/src/lib/components/formly.field.ts
src/ui/bootstrap/addons/src/addons.component.ts
src/ui/bootstrap/form-field/src/form-field.wrapper.ts
src/ui/ionic/form-field/src/form-field.wrapper.ts
src/ui/kendo/form-field/src/form-field.wrapper.ts
src/ui/material/form-field/src/form-field.wrapper.ts
src/ui/nativescript/form-field/src/form-field.wrapper.ts
src/ui/ng-zorro-antd/form-field/src/form-field.wrapper.ts
src/ui/primeng/form-field/src/form-field.wrapper.ts

fix(core): remove OnPush change detection in wrappers

---

demo/src/app/examples/advanced/datatable-integration/datatable.type.ts
src/core/src/lib/templates/field-array.type.ts
src/core/src/lib/templates/field.type.ts

fix(core): allow override typing for field property in FieldArrayType

---

demo/src/app/app.component.ts
demo/src/app/guides/custom-formly-field.md
src/core/src/lib/components/formly.field.spec.ts
src/core/src/lib/models/fieldconfig.ts
src/core/src/lib/services/formly.config.spec.ts
src/core/src/lib/services/formly.config.ts
src/core/src/lib/utils.ts
src/ui/material/form-field/src/field.type.ts

feat(core): allow passing component to the field definition

---

demo/src/app/guides/custom-formly-wrapper.md
src/core/src/lib/components/formly.field.spec.ts
src/core/src/lib/components/formly.field.ts
src/core/src/lib/models/fieldconfig.ts
src/core/src/lib/services/formly.config.ts

feat(core): allow passing wrapper component to the field definition

---

src/core/json-schema/src/formly-json-schema.service.spec.ts
src/core/json-schema/src/formly-json-schema.service.ts

fix(json-schema): improve oneOf selection of mixed type

---

src/core/select/src/public_api.ts

feat(core): export FormlySelectOptionsPipe

---

src/ui/material/datepicker/src/datepicker.type.ts

fix(material): detect changes of datepicker opened property

---

src/core/src/lib/components/formly.field.config.ts
src/core/src/lib/extensions/field-expression/field-expression.spec.ts
src/core/src/lib/extensions/field-expression/field-expression.ts

fix(core): improve eval array notation in expressions

---

src/core/src/lib/templates/field-array.type.spec.ts
src/core/src/lib/templates/field-array.type.ts

fix(core): emit valueChanges when fieldArray length is decreasing

---

src/core/src/lib/extensions/core/core.ts
src/core/src/lib/models/fieldconfig.ts
src/core/src/lib/templates/field.type.ts
src/core/src/lib/templates/formly.attributes.ts
src/ui/material/form-field/src/field.type.ts
src/ui/material/form-field/src/form-field.wrapper.ts

fix(core): remove additionalProps from FormlyFieldProps interface

---

demo/src/app/ui/ui-primeng/config.module.ts
demo/src/app/ui/ui-primeng/select/app.component.html
demo/src/app/ui/ui-primeng/select/app.component.ts
demo/src/app/ui/ui-primeng/select/app.module.ts
demo/src/app/ui/ui-primeng/select/index.ts

docs(primeng): remove broken multiselect example

---

UPGRADE-6.0.md
src/core/src/lib/models/config.ts

docs: fix v6 documentation

---

src/core/select/src/select-options.pipe.spec.ts
src/core/select/src/select-options.pipe.ts

fix(core): handle passing undefined to select options pipe

---

src/core/src/lib/extensions/field-form/field-form.spec.ts
src/core/src/lib/extensions/field-form/field-form.ts
src/core/src/lib/templates/field-array.type.spec.ts

fix(core): trigger validation in ArrayType on field update

---

src/core/src/lib/templates/formly.validation-message.ts

fix(core): detect validation message changes in expressionProperties

---

src/core/src/lib/components/formly.attributes.spec.ts
src/core/src/lib/components/formly.attributes.ts

fix(core): detect changes when focusing a repeatable field

---

src/core/src/lib/templates/field-array.type.ts

fix(core): sync fieldGroup length on FieldArrayType remove

---

src/core/src/lib/components/formly.form.spec.ts
src/core/src/lib/extensions/field-form/field-form.ts

fix(core): update form validity of nested key field

---

src/core/src/lib/components/formly.field.ts
src/core/testing/src/utils.ts

fix(core): detect changes of formState

---

src/core/select/src/select-options.pipe.ts

fix(core): detect change of expressionChanges in formlySelectOptions

---

docs/expression-properties.md

docs: add expression changes event section

---

package.json
src/core/src/lib/components/formly.field.spec.ts
src/core/src/lib/components/formly.field.ts
src/core/src/lib/extensions/field-expression/field-expression.spec.ts
src/core/src/lib/extensions/field-expression/field-expression.ts
src/core/src/lib/models/fieldconfig.cache.ts

fix(core): improve handling expression updates

---

src/core/src/lib/templates/field-array.type.spec.ts
src/core/src/lib/templates/field-array.type.ts

fix(core): detect changes of connected fields in array type

---

angular.json
package.json
src/core/src/lib/components/formly.field.spec.ts
src/core/src/lib/components/formly.field.ts
src/core/src/lib/extensions/field-expression/field-expression.ts

fix(core): detect changes of observable expressions

---

src/ui/bootstrap/radio/src/radio.type.ts
src/ui/kendo/radio/src/radio.type.ts
src/ui/ng-zorro-antd/radio/src/radio.type.ts
src/ui/primeng/radio/src/radio.type.ts

fix(core): support disabled radio option in Angular v15

---

src/ui/material/slider/src/slider-input.ts
src/ui/material/slider/src/slider-mdc.type.ts
src/ui/material/slider/src/slider.module.ts
src/ui/material/slider/src/slider.type.ts

fix(material): support thumb label in slider type

---

src/core/src/lib/templates/field-array.type.spec.ts
src/core/src/lib/templates/field-array.type.ts

fix(core): ensure the model is a valid array for FieldArrayType

---

src/ui/material/form-field/src/form-field.module.ts
src/ui/material/form-field/src/form-field.wrapper.ts

fix(material): add subscriptSizing support for FormField

---

src/ui/material/form-field/src/field.type.ts
src/ui/material/select/src/select.type.ts

fix(material): fix select overlay position

---

demo/src/app/examples/other/material-prefix-suffix/addons.wrapper.ts
src/ui/material/form-field/src/field.type.ts
src/ui/material/form-field/src/form-field.wrapper.ts

fix(material): add support of text prefix / suffix

---

src/ui/kendo/package.json

this makes any available version of kendo ui compatible for the library
#3571 
any version of kendo above the minimum will be accepted

fix(kendo): update peer dependencies

---

docs/getting-started.md

Update getting-started.md - correct small typo

---

src/core/src/lib/extensions/field-form/field-form.spec.ts
src/core/src/lib/extensions/field-form/field-form.ts

fix(core): ensure disabled prop is working for field without key

---

src/core/src/lib/utils.ts

fix(core): ensure observe prop is defined before calling defineProperty

---

src/core/src/lib/components/formly.field.ts
src/core/src/lib/extensions/field-expression/field-expression.spec.ts
src/core/src/lib/extensions/field-expression/field-expression.ts
src/core/src/lib/utils.ts

fix(core): supports nested model assign in expressions

---

src/core/src/lib/components/formly.field.ts
src/core/src/lib/extensions/field-form/field-form.spec.ts
src/core/src/lib/extensions/field-form/field-form.ts

fix(core): delegate FormArray creation to FieldArrayType only

---

src/core/src/lib/templates/field-array.type.ts

fix(core): call register control on fieldArray update

---

src/ui/material/checkbox/src/checkbox.type.spec.ts
src/ui/material/checkbox/src/checkbox.type.ts
src/ui/material/datepicker/src/datepicker.type.ts
src/ui/material/input/src/input.type.spec.ts
src/ui/material/input/src/input.type.ts
src/ui/material/native-select/src/native-select.type.ts
src/ui/material/textarea/src/textarea.type.spec.ts
src/ui/material/textarea/src/textarea.type.ts
src/ui/material/toggle/src/toggle.type.ts

fix(material): add missing name attribute

---

src/ui/material/checkbox/src/checkbox.type.ts
src/ui/material/form-field/src/field.type.ts

fix(material): update focus state after interacting with checkboxes

---

src/core/src/lib/components/formly.field.spec.ts
src/core/src/lib/components/formly.field.ts
src/core/src/lib/models/fieldconfig.cache.ts
src/core/src/lib/templates/field.type.ts

fix #3455 #3527 #3524 #3549 #1222

fix(core): detect valueChanges of local field controls

---

src/ui/ng-zorro-antd/form-field/src/form-field.wrapper.ts

Description prop support for ng-zorro-antd
fix #3639

feat(ng-zorro-antd): description support for ng-zorro-antd

---

src/ui/material/checkbox/src/checkbox.type.ts
src/ui/material/form-field/src/form-field.wrapper.ts

fix(material): use correct CSS class for form field required marker

---

src/core/src/lib/components/formly.form.ts
src/core/src/lib/utils.ts

fix(core): detect model changes for zoneless change detection

---

src/core/src/lib/extensions/field-form/field-form.spec.ts
src/core/src/lib/extensions/field-form/field-form.ts

fix(core): override initial defaultValue on build

---

src/core/src/lib/extensions/core/core.ts
src/core/src/lib/extensions/field-expression/field-expression.ts
src/core/src/lib/services/formly.builder.ts
src/core/src/lib/templates/field-array.type.spec.ts
src/core/src/lib/utils.ts

fix(core): ensure defaultValues is set on new nested item added to array

---

src/ui/primeng/datepicker/src/datepicker.type.ts

fix(primeng): set default value for datepicker numberOfMonths

---

src/ui/ionic/input/src/input.type.ts

fix(ionic): add missing input label for type: 'number'

---

src/core/json-schema/src/formly-json-schema.service.ts

fix(json-schema): fix optional type number validation

---

src/core/json-schema/src/formly-json-schema.service.spec.ts
src/core/json-schema/src/formly-json-schema.service.ts
src/core/src/lib/components/formly.field.ts

fix(json-schema): fix type number validation error

---

src/core/json-schema/src/formly-json-schema.service.spec.ts
src/core/json-schema/src/formly-json-schema.service.ts

fix(json-schema): unset required pros to array type

---

src/core/json-schema/src/formly-json-schema.service.spec.ts
src/core/src/lib/components/formly.field.ts

fix(core): ensure parser is called on each model update

---

src/core/json-schema/src/formly-json-schema.service.spec.ts
src/core/json-schema/src/formly-json-schema.service.ts

fix(json-schema): apply default value for array items

---

src/core/src/lib/components/formly.field.ts

fix(core): ensure validation is working in Angular v18.1

---

src/core/src/lib/components/formly.field.spec.ts
src/core/src/lib/components/formly.field.ts
src/core/src/lib/components/formly.form.ts

Bug fix
https://github.com/ngx-formly/ngx-formly/issues/3984

fix: performance decline issue

---

README.md

docs
Link to https://v17.angular.io/guide/reactive-forms
Link to https://angular.dev/guide/forms/reactive-forms

docs(README.md): link

---

src/core/src/lib/components/formly.form.ts
src/core/src/lib/services/formly.config.ts

fix(core): clear component refs on FormlyForm destroy
