ngx-formly/ngx-formly

- demo/template.html
- src/components/formly.form.ts
Hi,
I would like to use `ngSubmit` and I figured out that is not possible with the current implementation, so I propose to not include `form` in the `formly-form` to allow more flexibility.
thanks in advance :smile:
> feat(formly-form): move `form` out of `formly-form` component.

- demo/hello.ts
- demo/template.html
- src/components/formly.common.component.ts
- src/components/formly.field.ts
- src/components/formly.form.ts
- src/services/formly.event.emitter.ts
- src/services/formly.field.builder.ts
- src/services/formly.field.delegates.ts
- src/templates/field.ts
- src/templates/formlyfield.checkbox.ts
- src/templates/formlyfield.input.ts
- src/templates/formlyfield.multicheckbox.ts
- src/templates/formlyfield.radio.ts
- src/templates/formlyfield.select.ts
- src/templates/formlyfield.textarea.ts
The model changes are now triggered from [FormControl::valueChanges](https://github.com/angular/angular/blob/master/modules/%40angular/forms/src/model.ts#L206) instead of doing that manually!
> fix(formlyField): fixed two way Data Binding issue

- demo/hello.ts
- src/components/formly.form.ts
Nested keys were supported to some degree as in the model would update
but it would not properly set the form control.
This was due the fact that the formgroup would not nest when a
fieldgroup was specified.
This was fixed by making registerFormControls context sensitive in the
sense that the nested model and nested formgroup will be passed if in
the formfieldconfig the key was specified.
Updated the demo to showcase that indeed the value will be set at the
start.
> fix(#121): support nested keys

- .all-contributorsrc
- README.md
- package.json
Contributors section with information of myself, @aitboudad @divyakumarjain @Pouja @ckniffen, @Riron and @thiagogjt updated
Use `all-contributors-cli` to add and generate contributors
install using 
`npm install all-contributors-cli -g`
> chore(Contributors) Add allcontributors to add contribution to readme

- .npmignore
- src/core/core.ts
**What is the current behavior? https://github.com/formly-js/ng2-formly/issues/239#issuecomment-260175676**
> fix(npmignore): allow `src` folder

- src/core/components/formly.field.spec.ts
- src/core/components/formly.field.ts
> fix(FormlyField): subscribe to FormControl only when field has a key

- src/ui-bootstrap/types/select.ts
Feature
[https://github.com/formly-js/ng2-formly/issues/258](#258)
adds labelProp and valueProp to template options on the bootstrap select type similar to the angular-formly-templates-bootstrap select type
change select type to use labelProp and valueProp template options (similar to angular-formly-templates-bootstrap)
> feat(#258) valueProp and labelProp in type select

- src/core/services/formly.form.builder.spec.ts
- src/core/services/formly.form.builder.ts
https://github.com/formly-js/ng2-formly/issues/282
> fix(#282): fixed merge field options with nested property key

- demo/hello.ts
- src/core/components/formly.attributes.spec.ts
- src/core/components/formly.attributes.ts
- src/core/components/formly.field.config.ts
fix
Closes #279 
Include events in template options
> fix(Config) have the events in templateOptions

- src/core/components/formly.field.config.ts
- src/core/services/formly.field.delegates.ts
Feature
When hideExpression is a function, `this` and `args` of the function are inconsistent with the context when the expression is a string and does not seem to provide useful access to the field.
When hideExpression is a function it is called with the same `this` and `args` as it would be if it were a string.
This may not be necessary when a hideExpression function is declared in the …
> feat(HideExpression) add consistent context to function expression

- src/core/components/formly.field.spec.ts
- src/core/components/formly.field.ts
- src/core/services/formly.expression.ts
- src/core/services/formly.field.delegates.ts
Feature
ExpressionProperties only accept strings - see #148 
ExpressionProperties accept strings, booleans and functions - as hideExpression
> Expression properties should be able to take function (#148)

- demo/repeatedSection.ts
- src/core/components/formly.field.spec.ts
- src/core/components/formly.form.spec.ts
- src/core/components/formly.form.ts
- src/core/components/formly.group.ts
- src/core/services/formly.form.builder.ts
- src/core/utils.spec.ts
- src/core/utils.ts
fix #288 
Can't reset RepeatSection
Reset of FormArray in the this.form 
> fix(reset) FormArray reset

- demo/hello.ts
- src/core/services/formly.form.builder.spec.ts
- src/core/services/formly.form.builder.ts
- src/ui-bootstrap/types/radio.ts
Bug fix
#301
- [ X] The commit messages follow our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
When a Radiobutton control is attached to a nested property, an error is
thrown
because the formControlName in FormlyField is nested. We fixed this by
using formControl
instead of formControlName.
We fixed also some more general issues with the …
> fix: Allow for nested properties in Radiobutton

- demo/hello.ts
- demo/repeatedSection.ts
- demo/template.html
- src/core/components/formly.form.ts
- src/core/services/formly.form.builder.ts
- src/core/utils.spec.ts
- src/core/utils.ts
feature
The repeatSection / fieldArray does not behave well when the model is changed after the form's been built (i.e. bind fields to the form and with a setTimeout bind the model some time later).  Nor does it reset nicely if its key is a path.  See this plunker which uses the latest build of formly:
https://plnkr.co/edit/xXYQcdNFDGj9mcdaoT50?p=preview
Updated the form builder's handling of field arrays with the intent of handling paths better.
Updated the form's option.resetModel to accept an optional model to reset the form with; similarly have made efforts to enable this to preserve parts of the model …
> feat(resetModel): update options.resetModel to accept an optional model

- src/core/components/formly.form.ts
Bug fix
When options.resetModel is used to reset the model, parts that would add controls to a FormArray are not updated such that valueChanges would be wired up.
The options.resetModel's FormArray reset's been updated to use the FormArray's properties and methods for manipulating its underlying controls as opposed to manipulating the controls array directly.
fixes issue related to #344 when the options.resetModel is used
> fix(resetModel): update options.resetModel to reset FormArrays correctly

- src/core/services/formly.form.builder.ts
> fix(validation): merge field default options before init validation.

- demo/horizontal.wrapper.ts
- demo/panel.wrapper.ts
- src/core/components/formly.field.spec.ts
- src/core/components/formly.field.ts
- src/ui-bootstrap/types/select.ts
- src/ui-bootstrap/wrappers/addons.ts
- src/ui-bootstrap/wrappers/description.ts
- src/ui-bootstrap/wrappers/fieldset.ts
- src/ui-bootstrap/wrappers/label.ts
- src/ui-bootstrap/wrappers/message-validation.ts
in angular v4 `template` is deprecated in favor of `ng-template` and there is no way to change it without breaking change. Replacing it with `ng-container` would allow us to support both v2 and v4.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/383)
> feat(FormlyField): use `ng-container` instead of deprecated `template`.

- src/ui-bootstrap/types/select.ts
Feature
Select has not disable configuration
Disable select option when add disabled: true to configuration
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/407)
> Add disabled feature to select type

- README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/369)
> chore(readme):  fix bootstrap template repo link

- demo/src/app.component.ts
- demo/src/formly/types/repeatedSection.ts
- src/core/components/formly.field.config.ts
- src/core/components/formly.form.ts
- src/core/components/formly.group.ts
**What kind of change does this PR introduce? Bug fix, feature**
I decided to keep the className for `FormlyForm` even if `fieldGroup` is present this will introduce a BC break but we don't have a choice:
- when using `className` it should refer to the root element `<formly-field>`
- in order to apply className for  `<formly-form>` when using `fieldGroup` you should define the class name in `fieldGroupClassName` option.
```ts
className: 'row',
fieldGroup: ...
```
```ts
fieldGroupClassName: 'row',
fieldGroup: ...
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/442)
> fix(FormlyForm): allow className even if fieldGroup is set

- src/core/services/formly.form.builder.spec.ts
- src/core/services/formly.form.builder.ts
Fix
Currently formly doesn't allow you to have optional fields with min/max. It also doesn't allow you to have equal values
The new behavior allows you to have optional fields and equal values
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/449)
> fix(validation) allow null/empty and equal values in min/max validation

- src/core/src/services/formly.config.ts
Bug fix of deprecated function OpaqueToken see: https://github.com/angular/angular/blob/d169c2434e3b5cd5991e38ffd8904e0919f11788/modules/%40angular/core/src/di/injection_token.ts#L29
**What is the current behavior?**
Not working on angular 5 because of deprecated function
**What is the new behavior?**
Working on angular 5.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/508)
> fix: replace deprecated OpaqueToken with InjectionToken

- package.json
- src/core/src/templates/field.ts
- src/ui-bootstrap/src/types/input.ts
- src/ui-bootstrap/src/wrappers/fieldset.ts
- src/ui-bootstrap/src/wrappers/message-validation.ts
**What kind of change does this PR introduce? Bug fix, feature**
**What is the current behavior?**
`valid` was wrongly implemented it get the opposite value of what we expected (if valid return **false**, if not valid return **true**)
`showError` will be used instead of `valid` (to be removed in `v2`)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/532)
> feat(field): deprecated valid in favor of showError.

- src/core/src/templates/field.ts
BREAKING CHANGE: `Field::valid` is no longer available, use `showError` instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ng-formly/537)
> feat(field): remove deprecated `valid` prop.

- src/core/src/components/formly.field.ts
- src/core/src/components/formly.form.spec.ts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/588)
> fix(hideExpression): use getFieldModel only for simple field

- tsconfig.json
Angular modules added to "paths" section of tsconfig.json in order to avoid "Error encountered
resolving symbol values statically. Calling function 'InjectionToken', function calls are not
supported." error
fix #605
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/606)
> fix(tsconfig.json): Angular modules added to "paths"

- src/ui-material/src/wrappers/form-field.ts
Feature, fix #604
Material design labels do not show an asterisk when field is required (as the bootstrap do).
Material design labels now show an asterisk as the bootstrap labels do.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/609)
> feat(label): Add an asterisk to ui-material fields when required

- src/core/src/components/formly.form.ts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/626)
> fix(core): avoid calling deepMerge for readonly property.

- src/ui-material/src/types/checkbox.ts
- src/ui-material/src/types/input.ts
- src/ui-material/src/types/multicheckbox.ts
- src/ui-material/src/types/radio.ts
- src/ui-material/src/types/select.ts
Fixes material field types not calling lifecycle hooks due to method overrides
Bug fix
Material field types that implement Angular lifecycle hooks do not call the corresponding field lifecycle hook.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/628)
> fix(material): ensure calls to lifecycle hooks

- src/core/src/services/formly.config.ts
- src/core/src/services/formly.form.builder.spec.ts
- src/core/src/services/formly.form.builder.ts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/630)
> fix(core): add default wrappers when type is set

- src/ui-bootstrap/src/wrappers/label.ts
fix #633
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/637)
> fix(bootstrap): add missing `control-label` class for label

- package.json
- src/ui-bootstrap/package.json
- src/ui-bootstrap/src/types/checkbox.ts
- yarn.lock
BREAKING CHANGE: bootstrap 4.0.0-beta is no longer supported.
fix #679
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/680)
> feat(bootstrap): support bootstrap 4.0.0

- src/core/src/components/formly.field.config.ts
Solve the issue [Parsers as array of functions declaration](https://github.com/formly-js/ngx-formly/issues/684)
[Parsers as array of functions declaration](https://github.com/formly-js/ngx-formly/issues/684)
- [*] My code has been linted. (`npm run lint` to do this. `npm run build` will fail if there are files not linted.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/685)
> Fix Issue: parsers as array of functions declaration #684

- src/core/src/services/formly.form.expression.ts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/713)
> fix(core): ensure passing a valid model in checkField expression.

- src/core/src/components/formly.form.spec.ts
- src/core/src/services/formly.form.builder.ts
- src/core/src/services/formly.form.expression.ts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/721)
> feat(core): support using `className` in expressionProperties.

- src/ui-bootstrap/src/wrappers/label.ts
Small fix to not display the `<label>` element when the parameter is not set in the `templateOptions` property.
Currently the element is displayed even when the value is empty, this leads to some extra empty space between the inputs. 
After this PR the white space is not displayed anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> fix(bootstrap): don't render label when the templateOption is not set

- src/core/src/components/formly.form.spec.ts
- src/core/src/services/formly.form.expression.ts
- src/core/src/utils.ts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/735)
> fix(FormlyFormExpression): ensure toggling formControl when key contains array syntax

- src/core/src/components/formly.attributes.spec.ts
- src/core/src/components/formly.attributes.ts
- src/core/src/components/formly.field.config.ts
There is no way to allow rendering extra html attribures
Introduce `attributes` options which allow users to specify which option in `templateOption` can be used as an attribute.
for example for range type we can use:
```ts
{
key: 'age',
type: 'input',
templateOptions: {
attributes: {
min: 5,
max: 10,
},
}
}
```
we can also set those attributes globally in formly declaration:
```ts
FormlyModule.forRoot({
types: [
{
name: 'range',
extends: 'input',
defaultOptions: {
templateOptions: {
type: 'range',
attributes: {
min: 5,
max: 10,
},
},
},
},
],
}),
```
---
This change is [<img …
> feat(core): allow rendering extra attributes

- src/core/src/components/formly.attributes.spec.ts
- src/core/src/components/formly.attributes.ts
Bug fix
Running our project with the latest version of ngx-formly resulted in the error below, because it tried to read the `attributes` property from `templateOptions` which does not always exist.
```
TypeError: Cannot read property 'attributes' of undefined
at FormlyAttributes.ngOnChanges (webpack:///src/core/src/components/formly.attributes.ts:26:43 <- .config/karma-shim.js:32185:14434)
at checkAndUpdateDirectiveInline (webpack:///node_modules/@angular/core/@angular/core.es5.js:10840:0 <- .config/karma-shim.js:11305:19)
at checkAndUpdateNodeInline (webpack:///node_modules/@angular/core/@angular/core.es5.js:12341:0 <- …
```
> fix(core): only read attributes property if templateOptions are set

- karma.conf.js
- src/core/src/components/formly.form.spec.ts
- src/core/src/components/formly.form.ts
Otherwise there's the issue that form fields don't get properly
recreated (i.e. form array parts)
Fixes #768
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/770)
> fix(core): reset model on each change

- demo/src/app/examples/examples.component.ts
- demo/src/app/examples/examples.module.ts
- demo/src/app/examples/other/observable-select/app.component.html
- demo/src/app/examples/other/observable-select/app.component.ts
- demo/src/app/examples/other/observable-select/app.module.ts
- demo/src/app/examples/other/observable-select/config.module.ts
- demo/src/app/examples/other/observable-select/data.service.ts
- src/core/src/components/formly.field.config.ts
- src/ui-bootstrap/src/types/multicheckbox.ts
- src/ui-bootstrap/src/types/select.spec.ts
- src/ui-bootstrap/src/types/select.ts
- src/ui-material/src/types/multicheckbox.ts
- src/ui-material/src/types/select.ts
Feature.
See #693
Now it's possible to bind `Observable` streams to the `options` property of `type: 'select'` fields.
Also added a new demo example.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/772)
> feat(core): allow binding Observables to select options

- src/core/src/services/formly.form.builder.spec.ts
- src/core/src/services/formly.form.builder.ts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/799)
> fix(core): `addFormControl` apply patchValue only for FormControl instance.

- demo/src/app/examples/advanced/repeating-section/app.component.ts
- demo/src/app/examples/advanced/repeating-section/repeat-section.type.ts
- src/core/src/components/formly.group.ts
Added ng-content to formly-group. So that users can add content inside the field group such as Remove button.
#840 
Users able to add html content inside field group
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/843)
> Added ng-content to formly-group. Updated Examples to inline remove btn

- demo/src/app/examples/other/cascaded-select/app.component.ts
Add a predefined value in cascaded select example.
See #846.
Docs update
**Other information**: -
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/849)
> demo: add startWith to cascaded select example

- package.json
- src/core/src/services/formly.form.builder.spec.ts
- src/core/src/services/formly.form.expression.spec.ts
- src/core/src/test-utils.ts
- src/ui-material/src/types/select.spec.ts
Add unit tests for newly abstracted service.
See https://github.com/formly-js/ngx-formly/issues/711
Tests
I'm fairly new to this library so I didn't create any stubs instead I copied over several setup functions from Form Builder. I tried to keep it at a minimum but I don't think it's very sustainable, so this PR is open for discussion :) Also, I haven't tested more complicated `FormGroup` …
> test(FormlyFormExpression): add test for service

- src/core/src/components/formly.form.spec.ts
- src/core/src/services/formly.form.builder.spec.ts
- src/core/src/services/formly.form.builder.ts
- src/core/src/services/formly.form.expression.spec.ts
- src/core/src/services/formly.form.expression.ts
fix #844, fix #851
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/850)
> fix(core): skip managing FormGroup status when it has children.

- src/core/package.json
- src/core/src/components/formly.form.ts
- src/ui-bootstrap/src/types/select.spec.ts
- src/ui-bootstrap/src/types/select.ts
- src/ui-material/src/types/select.spec.ts
- src/ui-material/src/types/select.ts
BREAKING CHANGE: droped Angular 4 support + rxjs version should >= 5.5.8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/857)
> feat(core): use rxjs lettable operators.

- src/core/src/components/formly.form.spec.ts
- src/core/src/services/formly.form.builder.ts
- src/core/src/services/formly.form.expression.ts
```patch
field.expressionProperties = {
-  'field.className': ...
+  'className': ...
}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/863)
> feat(code): allow using key expression property without passing `field` path.

- src/core/src/components/formly.attributes.spec.ts
- src/core/src/components/formly.attributes.ts
- src/core/src/components/formly.field.spec.ts
- src/core/src/components/formly.form.spec.ts
- src/core/src/templates/field.ts
- src/core/src/templates/formly.validation-message.spec.ts
- src/ui-bootstrap/src/types/select.spec.ts
- src/ui-material/src/types/select.spec.ts
fix #642
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/862)
> feat(core): remove `formControl` input in FormlyAttributes.

- src/core/src/services/formly.config.ts
fix #877
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/878)
> fix(core): use `Field` instead `FormlyFieldConfig` in showError

- src/ui-bootstrap/src/wrappers/addons.ts
fix #656
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/882)
> fix(bootstrap): apply border radius for input when using addons

- src/core/src/services/formly.config.ts
- src/core/src/services/formly.form.builder.ts
https://github.com/formly-js/ngx-formly/issues/896
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/898)
> feat(core): Added field attribute in custom validation

- src/core/src/services/formly.form.builder.spec.ts
- src/core/src/services/formly.form.builder.ts
- src/core/src/templates/field-array.type.ts
BREAKING CHANGE: createControl in FieldArrayType has been removed
fix #909
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/912)
> feat(core): move createControl FieldArrayType to core

- src/ui-bootstrap/src/types/select.spec.ts
- src/ui-bootstrap/src/types/select.ts
- src/ui-material/src/types/select.spec.ts
- src/ui-material/src/types/select.ts
Bug fix ->This allows select type, the actual value to be an object
See example.
https://stackblitz.com/edit/ngx-formly-select-as-value?file=app/app.component.ts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/910)
> fix(bootstrap,meterial) Allow Select Type, Value to be a object

- src/core/src/components/formly.field.config.ts
- src/core/src/components/formly.form.ts
- src/core/src/services/formly.form.builder.spec.ts
- src/core/src/services/formly.form.builder.ts
- src/core/src/utils.spec.ts
- src/core/src/utils.ts
This adds model to field so that it can be exposed when referencing the field.
The model is not apart of the fieldconfig currently. I need it in the validation so I can compare hidden values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/formly-js/ngx-formly/911)
> feat(core) Ngx formly model to field

- src/material/datepicker/src/datepicker.type.ts
Update angular material datepicker to support min and max date, and add in demo for both scenario
feature
Material doesn't support min and max date from datepickerOptions
Material will support min and max date from datepickerOptions
>  feat(material): update datepicker to support min max

- demo/src/app/examples/advanced/repeating-section/repeat-section.type.ts
Docs update - Clears up some confusion regarding the button text in the [repeating-section example](https://formly-js.github.io/ngx-formly/examples/advanced/repeating-section).
Fix submitted due to https://github.com/formly-js/ngx-formly/issues/998
> docs(demo): use btnText in repeating-section

- src/core/src/lib/services/formly.form.builder.spec.ts
- src/core/src/lib/services/formly.form.builder.ts
> fix(core): avoid duplicate templateManipulator wrapper during rebuild

- src/core/src/lib/templates/formly.validation-message.ts
BREAKING CHANGE: 
`fieldForm` input in `FormlyValidationMessage` is removed
Before:
```html
<formly-validation-message [field]="field"  [fieldForm]="formcontrol"></formly-validation-message>
```
After:
```html
<formly-validation-message [field]="field"></formly-validation-message>
```
> feat(core): remove deprecated fieldForm input in FormlyValidationMessage

- .gitignore
- demo/src/app/examples/advanced/datatable-integration/app.component.html
- demo/src/app/examples/advanced/datatable-integration/app.component.ts
- demo/src/app/examples/advanced/datatable-integration/app.module.ts
- demo/src/app/examples/advanced/datatable-integration/config.module.ts
- demo/src/app/examples/advanced/datatable-integration/datatable.type.ts
- demo/src/app/examples/examples.component.ts
- demo/src/app/examples/examples.module.ts
- package.json
- yarn.lock
add docs with example of datatable integration 
ngx-datatable
issue: custom type with ngx-datatable #1061
@aitboudad  I added the example.
> docs(demo): add example of ngx-datatable integration

- src/kendo/src/lib/ui-kendo.config.ts
- src/kendo/src/lib/ui-kendo.module.ts
Small Bug Fix that corrects the name of the config object in the Kendo layout.
Unchanged.
Unchanged.
> fix(kendo): use KENDO prefix in config name

- src/material/input/src/input.type.ts
Bug fix for the `<input type="number" >` in the Material templates.
Currently the value emitted is a string:
```
{
"Input": "42"
}
```
New behavior outputs a number:
```
{
"Input": 42
}
```
Fixes issue mentioned in #729.
I've used the same implementation as in the [Bootstrap template](https://github.com/formly-js/ngx-formly/blob/master/src/bootstrap/src/lib/types/input.ts):
> fix(material): make sure input type number emits the correct value

- src/core/src/lib/templates/field.type.ts
- src/material/checkbox/src/checkbox.type.ts
- src/material/datepicker/src/datepicker.type.ts
- src/material/form-field/src/field.type.ts
- src/material/form-field/src/form-field.wrapper.ts
- src/material/input/src/input.type.ts
- src/material/multicheckbox/src/multicheckbox.type.ts
- src/material/native-select/src/native-select.type.ts
- src/material/radio/src/radio.type.ts
- src/material/select/src/select.type.ts
- src/material/slider/src/slider.type.ts
- src/material/textarea/src/textarea.type.ts
- src/material/toggle/src/toggle.type.ts
- src/material/tsconfig.lib.json
enhancement
https://github.com/formly-js/ngx-formly/issues/1276#issuecomment-443167320
No functionality was changed that would require a unit test. Mostly adjusting TypeScript to a strict ruleset.
> refactor(material): enable TypeScript strict mode

- package-lock.json
- src/bootstrap/src/lib/run/addon.ts
- src/bootstrap/src/lib/types/checkbox.ts
- src/bootstrap/src/lib/types/multicheckbox.ts
- src/bootstrap/src/lib/wrappers/addons.ts
- src/bootstrap/src/lib/wrappers/form-field.wrapper.ts
- src/bootstrap/tsconfig.lib.json
enhancement
TypeScript is not in strict mode. Discussed to enable it for `ngx-formly` in the issue: #1276
Enabling strict typescript mode for bootstrap.
No functionality was changed that would require a unit test. Mostly adjusting TypeScript to a strict ruleset.
> refactor(bootstrap): enable TypeScript strict mode

- angular.json
- src/core/json-schema/src/formly-json-schema.service.spec.ts
- src/core/json-schema/src/formly-json-schema.service.ts
- src/core/src/lib/components/formly.field.config.ts
Added Tests for full coverage of current covered features
Added support for minimum/maximum
Added todo for things needed to be supported in the future
Added logic to support key hierarchy so configs can be rearranged
Added json-schema to code coverage through angular.json config
closes formly-js/ngx-formly/#1056
test additions for #1056 
No tests exist and min/max are not supported
New tests exist and min/max are now supported.  Also added parent.child key relationships when creating the configs.
**Please provide a …
> test(core):  Tests for json-schema converter feature

- src/material/input/src/input.type.ts
Quick fix, just removing a duplicate setting of the `readonly` prop on the material input type. doesn't create any side effect.
> fix(material): remove duplicated readonly prop

- src/material/input/src/input.type.spec.ts
- src/material/input/src/input.type.ts
Fixes the `readonly` and `tabIndex` of the inputs of `type="number"` for the material theme.
Currently these have not been applied
nope, bugfix
Related: https://github.com/ngx-formly/ngx-formly/pull/1372
> fix(material): add readonly and tabindex to number input

- demo/src/app/examples/examples.component.ts
- demo/src/app/examples/examples.module.ts
- demo/src/app/examples/other/material-prefix-suffix/addons.extension.ts
- demo/src/app/examples/other/material-prefix-suffix/addons.wrapper.ts
- demo/src/app/examples/other/material-prefix-suffix/app.component.html
- demo/src/app/examples/other/material-prefix-suffix/app.component.ts
- demo/src/app/examples/other/material-prefix-suffix/app.module.ts
- demo/src/app/examples/other/material-prefix-suffix/config.module.ts
Add an example for using angular material suffix and prefix.
Fixes #1369
> docs: add an example for material suffix and prefix

- src/core/json-schema/src/formly-json-schema.service.spec.ts
- src/core/json-schema/src/formly-json-schema.service.ts
- src/core/src/lib/core.ts
As discussed in #1459 this adds 2 things
**deep merge of `widget.formlyConfig` property using the already existing algorithm
```
...
// map in possible formlyConfig options from the widget property
if (jsonSchema['widget'] && jsonSchema['widget'].formlyConfig) {
const widgetConfig = jsonSchema['widget'].formlyConfig;
field = reverseDeepMerge(field, widgetConfig);
}
...
```
The second thing is **the ability to pass in a `FormlyJsonschemaOptions` with a `map` function callback that allows to further customize the mapping of the formly field from the JSONSchema source.
@aitboudad There is an open question here, namely whether the …
> feat(core): deep merge widget prop & add map callback

- demo/src/app/guides/expression-properties.md
- src/core/src/lib/components/formly.field.config.ts
- src/core/src/lib/components/formly.form.spec.ts
- src/core/src/lib/extensions/field-expression/field-expression.ts
Add field argument to hideExpression and expressionProperties
fix #704
> feat(core): add field arg to hideExpression and expressionProperties

- src/material/select/src/select.type.ts
> feat(material): add disableOptionCentering support for mat-select

- demo/src/app/ui/common/select/app.component.ts
- src/material/select/src/select.module.ts
- src/material/select/src/select.spec.ts
- src/material/select/src/select.type.ts
This PR implements the new feature described in #1516 .
> feat(material): add select all option to multiselect

- src/material/datepicker/src/datepicker.type.ts
- src/material/form-field/src/field.type.ts
- src/material/form-field/src/form-field.wrapper.ts
Add support for datepickerTogglePosition which support prefix/suffix. By default, the icon is missing.
The toggle currently only supports suffix.
Support for prefix/suffix/none.
> feat(material): adds datepicker toggle positioning support

- demo/src/app/examples/advanced/json-schema/app.component.ts
- demo/src/app/examples/advanced/json-schema/assets/allOf_json
- demo/src/app/examples/advanced/json-schema/config.module.ts
- demo/src/assets/json-schema/allOf.json
- src/core/json-schema/src/formly-json-schema.service.spec.ts
- src/core/json-schema/src/formly-json-schema.service.ts
re #1459
adds combine schema allOf support.
none
merges allOf schema array objects into one
> feat(json-schema): adds allOf support

- src/core/src/lib/utils.spec.ts
- src/core/src/lib/utils.ts
its a fix, its also a clean up of PR #1720 and it fixes #1719 
see #1719
ensure the `clone` method creates an object of the same `type` when this type knows how to clone itself
for example, for a class Foo that implements a method `clone`
```ts
import { clone } from 'utils';
class Foo {
constructor(public name: string) {}
clone() { return new Foo(this.name); }
isFoo() { return true; }
}
const foo = new Foo('test');
const clonedFoo = clone(foo);
console.log(clonedFoo.name); // 'test'
console.log(clonedFoo.isFoo()); // true
```
but for a class that doesn't, the current …
> fix(core): better cloning

- src/core/json-schema/src/formly-json-schema.service.spec.ts
- src/core/json-schema/src/formly-json-schema.service.ts
- src/core/src/lib/templates/field-array.type.ts
> fix(json-schema): set valid fieldArray when additionalItems is empty

- demo/src/app/examples/other/cascaded-select/app.component.html
- demo/src/app/examples/other/cascaded-select/app.component.ts
Hello, this PR is composed by minor clean up in the `cascaded-selected` example. It:
- removes the `subscribe`s, `OnDestroy` and some unnecessary variables, css classes and inputs;
- changes wrong variable names;
- creates a model interface and use it instead of `any`.
> refactor: clean up cascaded-selected example

- src/core/src/lib/core.module.ts
Fixes ability to use ng9 due to new requirement that ModuleWithProviders is generic: https://github.com/angular/angular/pull/33187
> fix: make FormlyModule ModuleWithProviders generic for ng9 support

- src/core/src/lib/components/formly.form.spec.ts
- src/core/src/lib/components/formly.form.ts
> fix(core): ignore default debounce when using updateOn blur/submit

- src/core/json-schema/src/formly-json-schema.service.ts
- src/core/src/lib/components/formly.form.spec.ts
- src/core/src/lib/extensions/core/core.ts
- src/core/src/lib/extensions/field-expression/field-expression.ts
- src/core/src/lib/extensions/field-form/field-form.spec.ts
- src/core/src/lib/extensions/field-form/field-form.ts
- src/core/src/lib/extensions/field-form/utils.ts
- src/core/src/lib/templates/field-array.type.ts
- src/core/src/lib/utils.ts
- src/ui/bootstrap/checkbox/src/checkbox.type.ts
- src/ui/bootstrap/select/src/select.spec.ts
- src/ui/bootstrap/select/src/select.type.ts
- src/ui/material/checkbox/src/checkbox.type.ts
- src/ui/material/form-field/src/field.type.ts
- src/ui/material/native-select/src/native-select.type.ts
BREAKING CHANGE: The initial value of the created FormControl has been changed from `null` to
`undefined` to match the field model value.
re #1861
> feat(core): use undefined as defaultValue for control to match the model

- src/core/json-schema/src/formly-json-schema.service.ts
- src/core/src/lib/utils.spec.ts
- src/core/src/lib/utils.ts
> fix(core): use bind of the cloned object for enumerable getter

- src/core/src/lib/components/formly.form.ts
check if content is defined before accessing its properties
Bug fix
It breaks trying to access `nativeElement` property of `content`, but `content` is not defined.
N/A
N/A
Angular upgrade from v7.x.x to v8.0.0 in our project caused this bug. I believe this happens because angular introduced `static: true / false` concept for `@ViewChild`.
AngularJS: 1.6.5
Angular: 8.0.0
@ngx-formly/core: 5.5.4
> fix(core): check if content is defined

- src/material/radio/src/radio.type.ts
> fix(material): allow overriding tabindex on mat-radio-group

- src/material/textarea/src/textarea.type.ts
> fix(material): remove textarea autosize attributes when disabled

- src/core/src/lib/components/formly.form.spec.ts
- src/core/src/lib/components/formly.form.ts
> fix(core): keep order of value subscriptions consistent on rebuild

- src/ionic/src/lib/types/datetime.ts
Add `yearValues`, `hourValues` and `minuteValues`
Feature
Datepicker ignores yearValues, hourValues and minuteValues properties.
Datepicker now accepts those properties
> feat(ionic): add missing properties to datetime type

- src/material/toggle/src/toggle.type.ts
Feature
Color property is not forwarded from `templateOptions`.
Color property is forwarded from `templateOptions`.
Since Slide Toggle supports `color` like many other components, the implementation simply follows other type implementations.
> feat(material) mat-slide-toggle color support

- demo/src/app/ui/ui-material/slider/app.component.ts
- src/material/slider/src/slider.type.ts
Adds support for enabling `thumLabel` in material slider.
Step, max, min are supported on sliders through the templateOptions properties.
However, specifying whether the thumLabel is enabled or not is not supported.
You can enable the `thumLabel` via the templateOptions.
> feat(material): mat-slider thumbLabel support

- src/core/src/lib/components/formly.field.spec.ts
- src/core/src/lib/services/formly.form.builder.ts
Fix OnPush FieldTypes not being change detected on expressionProperties changes.
If ChangeDetectionStrategy.OnPush is used in a custom FieldType, then the templateOptions which are generated via expressionProperties, do not result in a changeDetection check.
If a expression property changes, the FieldType is change detected properly.
> fix(core): fix OnPush FieldTypes not being change detected

- src/ionic/src/lib/types/select.ts
there is a bug for ion-select when options are async, wrapping anything in an ng-container should be a workaround for this old bug
https://github.com/ionic-team/ionic/issues/19324
> fix(ionic): allow async options for ion-select

- src/core/src/lib/extensions/field-expression/field-expression.spec.ts
- src/core/src/lib/extensions/field-expression/field-expression.ts
> fix(core): resubscribe to expr prop when re-rendering the field

- src/ui/material/datepicker/src/datepicker.type.ts
Bug fix. Picker is not visible.
Picker opens with empty content.
Picker html template is correct.
> fix(material): removed double tag closing in datepicker type

- src/material/form-field/src/form-field.wrapper.ts
Bug fix
https://github.com/ngx-formly/ngx-formly/issues/2443
> fix(material): remove empty mat-prefix and mat-suffix

- src/core/src/lib/components/formly.form.ts
- src/core/src/lib/templates/field-array.type.spec.ts
>  fix(core): rely on internal model when model input is empty

- demo/src/app/examples/introduction/app.component.ts
Bug fix in the documentation
**What is the current behavior?**
The 'focus' feature does not work in the introduction example: https://stackblitz.com/angular/lvmnpkeaaqb and the _And look! This field magically got focus!_ description does not make any sense because of it.
> docs(demo): make the 'focus' work in the Introduction Example

- demo/src/app/examples/advanced/datatable-integration/app.component.ts
- demo/src/app/examples/advanced/grid-integration/app.component.ts
Bug fix on two example pages
Currently, the example pages for ag-grid integration and ngx-datatable integration include "Stock Identifier" labels that mess up formatting for the ngx-datatable  example and make the ag-grid example very hard to use:
I removed the labels to align the examples and make them look / work better.
No tests apply to this PR
**Screenshots after changes**
This was such a small fix that I decided not to open an issue.
> docs(demo): remove stock identifier label in two examples

- demo/src/app/ui/ui-primeng/app.component.scss
- demo/src/styles.scss
- package.json
Fix the missing icons on PrimeNG Demo.
The checkbox on PrimeNG Demo doesn't show the tick mark.
The checkbox on PrimeNG Demo shows the tick mark.
Before screenshot:
After screenshot:
> docs(demo): add missing icons for primeng components

- UPGRADE-6.0.md
I tried to add a migration guide for v6. I'm not sure if the fieldChanges change is a breaking change. 
@aitboudad if someone relied on #1901 they could mitigate it with extending the formGroup and formArray and setting the defaultValue, correct?
> feat(core): add v6 migration guide

- UPGRADE-6.0.md
- demo/src/app/examples/other/hide-fields-with-animations/app.module.ts
- src/core/src/lib/components/formly.field.spec.ts
- src/core/src/lib/components/formly.field.ts
- src/core/src/lib/extensions/field-expression/field-expression.ts
- src/core/src/lib/models/config.ts
- src/core/src/lib/services/formly.config.ts
- src/schematics/src/ng-add/index.ts
BREAKING CHANGE: The `lazyRender` option is enabled by default
> feat(core): lazy render hidden fields by default

- UPGRADE-6.0.md
- src/core/json-schema/src/formly-json-schema.service.ts
- src/core/src/lib/models/fieldconfig.cache.ts
- src/core/src/lib/models/fieldconfig.ts
- src/core/src/lib/services/formly.config.ts
BREAKING CHANGE: The `resetFieldOnHide` option is enabled by default
fix: #2570
> feat(core): allow control resetOnHide for a specific field

- UPGRADE-6.0.md
- src/core/json-schema/src/formly-json-schema.service.ts
- src/core/src/lib/components/formly.field.ts
- src/core/src/lib/components/formly.form.spec.ts
- src/core/src/lib/core.ts
- src/core/src/lib/extensions/core/core.ts
- src/core/src/lib/extensions/field-expression/field-expression.ts
- src/core/src/lib/extensions/field-form/field-form.ts
- src/core/src/lib/extensions/field-form/utils.ts
- src/core/src/lib/extensions/field-validation/field-validation.ts
- src/core/src/lib/services/formly.config.ts
- src/core/src/lib/templates/field-array.type.ts
BREAKING CHANGE: The `checkExpressionOn` option is set to `modelChange` instead of `changeDetectionCheck`
> feat(core): check expression on change only

- src/core/src/lib/templates/field.type.ts
- src/core/src/lib/templates/formly.attributes.ts
- src/ui/material/checkbox/src/checkbox.type.ts
- src/ui/material/form-field/src/field.type.ts
- src/ui/material/form-field/src/form-field.wrapper.ts
- src/ui/material/form-field/src/public_api.ts
- src/ui/material/multicheckbox/src/multicheckbox.type.ts
- src/ui/material/radio/src/radio.type.ts
- src/ui/material/slider/src/slider.type.ts
- src/ui/material/toggle/src/toggle.type.ts
- src/ui/material/tsconfig.lib.json
Feature Request: Use typing of templateOptions given in generic FormlyFieldConfig _F_ in `FieldType<F>.to`
The type of value accessor `FieldType.to` is always `FormlyTemplateOptions`, even when you provide additional typing.
```ts
export declare abstract class FieldType<F extends FormlyFieldConfig = FormlyFieldConfig> {
field: F;
get to(): FormlyTemplateOptions;
}
```
The return type of `to` is a `NonNullable` type of `templateOptions` of the generic field _F_ 
```ts
export declare abstract class FieldType<F extends FormlyFieldConfig = FormlyFieldConfig> {
field: F;
get …
```
> feat(core): add type of templateOptions accessor "to"

- src/core/json-schema/src/formly-json-schema.service.spec.ts
- src/core/json-schema/src/formly-json-schema.service.ts
The fix avoids that a key property (`widget.formlyConfig.key`) is overridden by the schema key.
The model key is always the property key from the json-shema.
The schema key is only set when no key property is given by `widget.formlyConfig`
no visual feature
I'm not sure if checking for empty `strings` or `arrays` would be useful.
> fix(json-schema): do not override widget.formlyConfig.key

- UPGRADE-6.0.md
- src/ui/bootstrap/addons/src/addons.component.ts
BREAKING CHANGE: The two first argument of `onClick` handler has been replaced by `field` instance.
fix #2617
> feat(bootstrap): change `add-on::onClick` callback signature

- demo/src/app/app.component.ts
- demo/src/app/examples/advanced/i18n-alternative/translate.extension.ts
- demo/src/app/guides/custom-formly-extension.md
- demo/src/app/guides/guides.component.ts
This PR adds a guide for one of the remaining big formly features: extensions.
In addition, I have updated an example for clarity.
> docs(guides): add custom extension guide

- demo/src/app/app.component.ts
- demo/src/app/examples/advanced/extending-field-types/app.component.html
- demo/src/app/examples/advanced/extending-field-types/app.component.ts
- demo/src/app/examples/advanced/extending-field-types/app.module.ts
- demo/src/app/examples/advanced/extending-field-types/config.module.ts
- demo/src/app/examples/examples.module.ts
Docs update: A new example that shows how to add a new field type that extends another.
> docs: add example for extending field types

- src/core/src/lib/extensions/field-expression/field-expression.spec.ts
- src/core/src/lib/extensions/field-expression/field-expression.ts
Bug Fix
Currently, if an implementing library solely relys on formControl.valueChanges to get values from the model, when an expression change occurs for the model, the data is not emitted.
Expression changes on model now emit events
> Emit event on expression change

- src/core/src/lib/extensions/field-expression/field-expression.spec.ts
- src/core/src/lib/extensions/field-expression/field-expression.ts
> Fix Remove Fdescribe from Expression Tests

- UPGRADE-6.0.md
Documentation update - fix typo: `field.templateOptions.loading = ...` should read `field.templateOptions = ...` in the UPGRADE-6.0.md docs.
n/a
n/a
> fix(upgrade): update incorrect spread operator in upgrade docs

- demo/src/app/app.component.ts
Docs: this PR aims to enhance the demo site's usability by changing the site's title for different pages.
When someone has multiple tabs open for the demo site, it's not clear which tab corresponds to which page. With this change the tab's content becomes unambiguous.
Every page has the same title:
Each page has a different title based on it's sidebar link's text (the first tab shows the index page):
> docs: change site title based on the opened page

- build/build.ts
- build/schematics.ts
- build/util.ts
Because they rely on linux/unix command line tools, the build scripts previously didn't work for windows.
Now, the functionality is reimplemented using Node.js functions that work in any environment.
> build: update build script for Windows

- demo/src/app/guides/custom-formly-extension.md
- src/core/src/lib/core.module.ts
- src/core/src/lib/models/config.ts
- src/core/src/lib/services/formly.builder.spec.ts
- src/core/src/lib/services/formly.config.ts
core feature
Currently, there is no way to specifically order extensions. It will happen implicitly, depending on the order in which they are defined. This quickly becomes intransparent when you enforce alphabetic sorting or define extensions throughout multiple modules where the loading order is not clear.
This PR introduces an optional `priority` property to the `FormlyExtension` type that enables you to control this behavior. Lower numbers are processed first, with formly's own extensions all get a value of `-1`. Default `priority` is `1`.
Let me know what you think of …
> feat(core): introduce priority to sort extensions

- src/core/src/lib/extensions/core/core.ts
- src/core/src/lib/extensions/field-expression/field-expression.ts
- src/core/src/lib/extensions/field-form/field-form.ts
- src/core/src/lib/extensions/field-validation/field-validation.ts
- src/core/src/lib/models/config.ts
What is the current behavior? (You can also link to an open issue here)**
Currently, the `FormlyExtension` type and the core extensions are marked as experimental. 
Extensions have been released for over 3 years now and have a prominent place in the docs. It's probably time to make them official for v6, dont' you agree @aitboudad?
Experimental markers are removed.
> refactor: remove experimental markers

- .eslintrc.json
- demo/src/app/examples/other/hide-fields-with-animations/app.component.ts
- demo/src/app/examples/other/input-file/file-value-accessor.ts
- demo/src/app/examples/validation/unique-value-async-validation/app.component.ts
- demo/src/app/ui/ui-bootstrap/config.module.ts
- demo/src/app/ui/ui-kendo/config.module.ts
- demo/src/app/ui/ui-material/config.module.ts
- demo/src/app/ui/ui-ng-zorro-antd/config.module.ts
- demo/src/app/ui/ui-primeng/config.module.ts
- demo/src/assets/stackblitz/main.ts
- src/core/json-schema/src/formly-json-schema.service.spec.ts
- src/core/json-schema/src/formly-json-schema.service.ts
- src/core/select/src/select-options.pipe.spec.ts
- src/core/src/lib/components/formly.field.spec.ts
- src/core/src/lib/components/formly.field.ts
- src/core/src/lib/components/formly.form.spec.ts
- src/core/src/lib/extensions/field-expression/field-expression.spec.ts
- src/core/src/lib/extensions/field-expression/field-expression.ts
- src/core/src/lib/extensions/field-validation/field-validation.ts
- src/core/src/lib/models/fieldconfig.cache.ts
- src/core/src/lib/templates/formly.attributes.spec.ts
- src/core/src/lib/utils.spec.ts
- src/core/testing/src/component-factory.ts
- src/ui/bootstrap/checkbox/src/checkbox.type.spec.ts
- src/ui/ionic/select/src/select.type.spec.ts
- src/ui/kendo/select/src/select.type.spec.ts
- src/ui/kendo/textarea/src/textarea.type.spec.ts
- src/ui/material/form-field/src/field.type.ts
- src/ui/ng-zorro-antd/radio/src/radio.type.spec.ts
Currently, the ESLint config contains some things which I think could be improved.
I updated the following things:
-  removed seemingly useless `"ignorePatterns": ["projects/**/*"]` config
-  Since it is consequently ignored throughout formly, disabled `@angular-eslint/no-conflicting-lifecycle`
-  added `@typescript-eslint/no-unused-vars` and updated many occurences of unused imports/vars/args. I enabled the option to bypass this rule by naming vars with a leading underscore
- fixed some small additional stuff
**Please provide a screenshot of this feature before and after your code changes, if …
> style: update eslint config and resulting source code changes

- src/core/json-schema/src/formly-json-schema.service.spec.ts
- src/core/json-schema/src/formly-json-schema.service.ts
> feat(json-schema): rely on minItems to pre-populate array default value

- src/core/select/src/public_api.ts
- src/core/select/src/select-options.pipe.ts
refactor
Currently, if you want to do something with the `ISelectOptions` that the select-options pipe returns, you have to copy it from formly.
Now, the public api of the select module contains a (renamed) `FormlySelectOptions` type.
> refactor(core): export renamed FormlySelectOptions type

- commitlint.config.js
chore
currently, if you work on the select feature, you have to use the scope "core"
"select" should be a scope just like "testing" because it is its own subpackage.
> chore: update commitlint scopes to include "select"

- UPGRADE-6.0.md
- src/ui/bootstrap/addons/src/addons.component.html
- src/ui/bootstrap/addons/src/addons.component.scss
- src/ui/bootstrap/addons/src/addons.component.ts
- src/ui/bootstrap/checkbox/src/checkbox.type.ts
- src/ui/bootstrap/form-field/src/field.type.ts
- src/ui/bootstrap/form-field/src/form-field.wrapper.ts
- src/ui/bootstrap/form-field/src/public_api.ts
- src/ui/bootstrap/input/src/input.type.ts
- src/ui/bootstrap/multicheckbox/src/multicheckbox.type.ts
- src/ui/bootstrap/radio/src/radio.type.ts
- src/ui/bootstrap/select/src/select.type.ts
- src/ui/bootstrap/textarea/src/textarea.type.ts
fix #3265
BREAKING CHANGE: To customize style of bootstrap types rely on `formly-wrapper-form-field` instead of the following selectors:
- `formly-wrapper-addons`
- `formly-field-checkbox`
- `formly-field-input`
- `formly-field-multicheckbox`
- `formly-field-radio`
- `formly-field-select`
- `formly-field-textarea`
> feat(bootstrap): support floating labels

- demo/src/app/examples/other/presets/config.module.ts
When I opened #3256 , there was a mistake in the example - salutation.preset.ts wasn't rendered.
I added it to the config module.
> docs(preset): add preset to visible files in example

- src/core/src/lib/models/config.ts
checkExpressionOn defaults to modelChange in v6.
> docs: fix v6 documentation

- src/core/src/lib/templates/field-array.type.ts
Fixes #3341. 
The FieldArrayTypeConfig type does not allow for a custom props value like FormlyFieldConfig does.
The FieldArrayTypeConfig type will now allow for a custom props value like FormlyFieldConfig does.
Looks like the types for this interface were overlooked in #3295.
> fix(core): fixed FieldArrayTypeConfig props declaration

- demo/src/app/ui/ui-primeng/config.module.ts
- demo/src/app/ui/ui-primeng/datepicker/app.module.ts
- src/ui/primeng/datepicker/src/datepicker.module.ts
- src/ui/primeng/datepicker/src/public_api.ts
- src/ui/primeng/src/lib/ui-primeng.module.ts
fix #3339
BREAKING CHANGE: primeng `datepicker` type has been removed from `FormlyPrimeNGModule`, use `FormlyDatepickerModule` instead.
```ts
import { FormlyDatepickerModule } from '@ngx-formly/primeng/datepicker';
@NgModule({
imports: [
...
FormlyDatepickerModule,
],
})
export class AppModule {}
```
> fix(primeng): remove datepicker from main module

- src/ui/material/form-field/src/form-field.wrapper.ts
Adding a bug fix for an error I had run into when using Material Formly where the import was one level too deep.
> fix(material): remove usage of form-field deep import path

- src/core/src/lib/models/fieldconfig.ts
bug
key 'expressions' inside interface can get string or function. the function had interface 
`  expressions?: {
[property: string]: string | ((field?: FormlyFieldConfig) => any) | Observable<any>;
};`
the ? in the function arg tell ts that field can be also 'undefined' and 
a)it is not true.
b)it force you to add check that field is not undefined in the code because if not will be collison with the types..
i remove the ? from the function arg and now field cant be optional undefined
unit test  - didnt do. just manual QA
npm run build/lint  - no.
> fix(core): set field arg required in expressions

- src/core/src/lib/models/fieldconfig.ts
Fix typo in deprecation message: minLength -> maxLength.
**No behaviour changes**
> docs: correct deprecation message

- UPGRADE-6.0.md
documentation fixes
**No behaviour changes**
> docs(upgrade): fix typos in v6 upgrade docs

- src/core/json-schema/src/formly-json-schema.service.spec.ts
- src/core/json-schema/src/formly-json-schema.service.ts
Fix(json-schema)
#3438
N/A
N/A
N/A
> fix(json-schema): retrieve other field value from f.model

- src/ui/kendo/input/src/input.type.ts
> fix(kendo): remove duplicate formControl directive in input type

- src/ui/material/form-field/src/form-field.wrapper.ts
Fixes typos in the form-field wrapper. See: https://github.com/ngx-formly/ngx-formly/pull/3510#discussion_r1089811506
> fix(material): fix typo "ng-containe" -> "ng-container"

- src/ui/material/slider/src/slider-input.ts
Hello 👋 
As part of our project, we are using Facebook's new Memlab tool to detect memory leaks in SPA applications and their libraries. While running the tool and analyzing the code of ngx-formly, we saw that your project does a very good job of ensuring that all async operations are cancelled when components destroy. However, as per Memlab execution results, we found some unremoved listeners, causing the memory to leak (screenshots below).
[before]
Hence we added the fix by adding & removing the listeners with proper references, and you can see the heap size and count of leaks reducing noticeably:
<br />
Basically `.bind()` creates a new function reference each time [1-5]; which means the reference passed to the add and remove …
> fix(material): use same reference for adding and removing event listener

- demo/src/app/app.component.ts
- demo/src/app/examples/advanced/json-schema/app.component.ts
- demo/src/app/examples/other/json-powered/app.component.ts
- demo/src/app/guides/guides.component.ts
Hello 👋 
As part of our project, we are using Facebook's new Memlab tool to detect memory leaks in SPA applications and their libraries. While running the tool and analyzing the code of ngx-formly, we saw that your project does a very good job of ensuring that all async operations are cancelled when components destroy. However, as per Memlab execution results, we found some unsubscribed subscriptions, causing the memory to leak (screenshots below).
[before]
Hence we added the fix by unsubscribing the subscriptions on component destruction, and you can see the heap size and count of leaks reducing noticeably:
<br />
Note. Host listener is used to ensure that ngOnDestroy is called not only when the class destroy, but also when the page …
> fix(demo): unsubscribe subscriptions to avoid memory leaks

- src/ui/kendo/package.json
What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)
this makes any available version of kendo ui compatible for the library
What is the current behavior? (You can also link to an open issue here)
https://github.com/ngx-formly/ngx-formly/issues/3571
What is the new behavior (if this is a feature change)?
any version of kendo above the minimum will be accepted
Please check if the PR fulfills these requirements
The commit messages follow our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
A unit test has been written for this change.
Running npm run build produced a successful build. (Unit testing can be done by running npm test;)
My code has been linted. (npm run lint to do this. npm run build will fail if …
> fix(kendo): update peer dependencies

- src/core/select/src/select-options.pipe.ts
What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)
Looks like that the functions return types on elect Options Pipe have the wrong types
labelProp was (any)=> any , it's changed to string
valueProp was (any)=>boolean, it's changed to any
disabledProp was (any)=> string, it's changed to boolean
What is the current behavior? (You can also link to an open issue here)
What is the new behavior (if this is a feature change)?
Please check if the PR fulfills these requirements
[X ] The commit messages follow our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
A unit test has been written for this change.
[X ] Running npm run build produced a successful build. (Unit testing can be done by running npm test;)
[X ] My …
> fix(core): select options pipe has wrong return types

- src/ui/material/select/src/select.type.spec.ts
- src/ui/material/select/src/select.type.ts
Feature
Cannot style the mat-options when using a formly select. Is there another way to do this with the current behaviour? 
Allows you to specify a class name to the mat-options. This enables the user to help theme the mat-select control. 
> feat(material): add panelClass to mat-select props

- src/core/src/lib/components/formly.field.ts
- src/core/src/lib/utils.spec.ts
- src/core/src/lib/utils.ts
Bug fix
After upgrading to v6 there were certain scenarios (mainly in tests of our system) where reassigning the full config many times in succession would result in the `source` of the utility function `observeDeep` to be called with `undefined`
This would result in an invalid unsubscribe function to be returned.
`source` is defined as `any` but the current code does not cater for handling the "falsy" scenario
When `source` is `undefined` or `null` an empty `unsubscribe` function is returned allowing callers to not crash.
> fix(core): handle undefined source observer

- src/ui/kendo/select/src/select.type.ts
kendo template has fixed value in primitive, if you need to pass an object on the value it makes an error 
#3529 
there will be a primitive prop value on kendo select props
- [X ] The commit messages follow our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [X ] Running `npm run build` produced a successful build. (Unit testing can be done by running `npm test`;)
- [X ] My code has been linted. (`npm run lint` to do this. `npm run build` will fail if there are …
> feat(kendo): add primitive option in props

- src/ui/bootstrap/checkbox/src/checkbox.type.spec.ts
- src/ui/bootstrap/checkbox/src/checkbox.type.ts
- src/ui/bootstrap/form-field/src/form-field.wrapper.ts
- src/ui/bootstrap/input/src/input.type.spec.ts
- src/ui/bootstrap/input/src/input.type.ts
- src/ui/bootstrap/multicheckbox/src/multicheckbox.type.ts
- src/ui/bootstrap/radio/src/radio.type.spec.ts
- src/ui/bootstrap/radio/src/radio.type.ts
- src/ui/bootstrap/select/src/select.type.spec.ts
- src/ui/bootstrap/select/src/select.type.ts
- src/ui/bootstrap/textarea/src/textarea.type.spec.ts
- src/ui/bootstrap/textarea/src/textarea.type.ts
This is a feature change to allow for screen reader to mention that an input is invalid and to read the validation error message that is paired with the form control.
The current behavior is to not use aria-invalid or aria-descibedby. [Here is the issue I created for this problem](https://github.com/ngx-formly/ngx-formly/issues/3737)
The new change will only affect screen readers in bootstrap. It will now read that an input is invalid once shown error is called, and it will also read the error message that is paired with the form control.
**Please check if the PR fulfills …
> feat(bootstrap): added aria tags for input validation (#3737)

- src/core/src/lib/extensions/field-form/field-form.spec.ts
- src/core/src/lib/extensions/field-form/field-form.ts
The array add operation was slow because the field build created an observable and set the asyncValidators, even when there were no async validators. This change checks if the async validators are present and then only sets them.
fix #3791
Improves the performance of array add operation, mentioned in the issue #3791
> perf(core): set the asyncValidators when async validators are present

- src/ui/bootstrap/form-field/src/form-field.wrapper.ts
- src/ui/bootstrap/multicheckbox/src/multicheckbox.type.spec.ts
- src/ui/bootstrap/multicheckbox/src/multicheckbox.type.ts
Commit 1: This bug fix is to have the aria-describedby and aria-isinvalid to be in the input tag and not the div tag for the multicheckbox form field.
Commit2: Added role tag to formly-validation-message. This lets a screen reader know to read out the message as it appears, instead of the second time visited.
Commit3: Added unit test for multicheckbox form field type. Added is-invalid class on showError.
Input validation errors are not being read by screen reader when presented.
> fix(bootstrap): update multicheckbox aria attr in input tag

- demo/src/app/ui/ui-primeng/select/app.component.ts
- src/ui/primeng/select/src/select.type.spec.ts
- src/ui/primeng/select/src/select.type.ts
New feature on PrimeNG select, adds the ability to enable search bar (filter property)
Filtering enabled on the demo page.
Currently if using PrimeNG select with formly, search bar is not available
By adding the 
`filter: true`
property to the props object a basic search bar will now be enabled
> feat(primeng): select filtering prop

- src/core/src/lib/utils.ts
detect model changes for zoneless change detection working in production builds
https://github.com/ngx-formly/ngx-formly/issues/3928
> fix(core): testing for NoopNgZone working in prod builds

- docs/custom-formly-field.md
docs update
Typo in the file name `input-field.type` in custom types docs
> docs(guides): typo in the custom types docs

- demo/src/app/examples/advanced/json-schema/app.module.ts
Use the proper property names `exclusiveMinimum` and `exclusiveMaximum` instead of `step`
docs update
Wrong parameter name used in functions `exclusiveMinimumValidationMessage` and `exclusiveMaximumValidationMessage`
Example app works properly
> docs: fix JSON schema example app validation messages

- src/core/testing/src/component-factory.ts
- src/core/testing/src/input.module.ts
> Note: Currently this changes produce build errors, as the workspace is still on Angular 13 which doesn't support the `standalone` component metadata just yet
Bug fix
Closes #4020
The components in the testing entry point are explicitly marked as `standalone: false`, so they work in Angular 19.
> fix(testing): mark components as standalone false

- src/core/preset/src/public_api.ts
Bug fix
The `provideFormlyPreset` is not present in the `core/preset` `public_api.ts` file and therefore cannot be imported to be used in the application/component providers.
`provideFormlyPreset` is now exported from the `public_api.ts` file
> Fix non-published preset provider

- src/ui/primeng/radio/src/radio.type.ts
Bug fix for PrimeNg
https://github.com/ngx-formly/ngx-formly/issues/4070
Fixes typo to ensure options in the radio button group are using the appropriate label.
> V7.0.0 alpha.1 primeng raido button fix

- README.md
- UPGRADE-7.0.md
- src/core/src/lib/extensions/core/core.ts
- src/core/src/lib/extensions/field-expression/field-expression.ts
- src/core/src/lib/models/fieldconfig.cache.ts
- src/core/src/lib/services/formly.builder.spec.ts
- src/core/src/lib/services/formly.builder.ts
BREAKING CHANGE: Deprecated `FormlyFormOptions` methods has been removed: `_markForCheck`, `_buildForm` and `_markForCheck`.
> feat(core): remove deprecated options methods

- src/core/src/lib/templates/formly.group.ts
- src/core/testing/src/input.module.ts
- src/ui/material/checkbox/src/checkbox.type.ts
- src/ui/material/form-field/src/form-field.wrapper.ts
- src/ui/material/input/src/input.type.ts
- src/ui/material/multicheckbox/src/multicheckbox.type.ts
- src/ui/material/native-select/src/native-select.type.ts
- src/ui/material/radio/src/radio.type.ts
- src/ui/material/select/src/select.type.ts
Refactor to use built-in control flow for core and material, which was made stable in angular v18
Uses *ngFor/*ngIf style control flow, which will be deprecated in angular v20
No change in behavior, except probably better performance
> refactor(core+material): convert to built-in control flow

- src/ui/ionic/input/src/input.type.ts
The old code that separates ion-input for number and non-number is now obsolete
Refactor
Same with current behavior
> refactor(ionic): remove redundant code in formly-field-ion-input
